ministryofjustice/laa-maat-court-data-api

- .gitignore
- aws/application/README.md
- aws/application/application.template
- aws/application/parameters/development-maat-cd-api-pipeline.json
- aws/application/parameters/production-maat-cd-api-pipeline.json
- aws/application/parameters/staging-maat-cd-api-pipeline.json
- aws/application/parameters/test-maat-cd-api-pipeline.json
- aws/application/parameters/uat-maat-cd-api-pipeline.json
- aws/pipeline/README.md
- aws/pipeline/maat-cd-api-deployment-pipeline.template
- aws/pipeline/parameters/maat-cd-api-deployment-pipeline-shared-services.json
- buildspec-lz.yml
- scripts/build.sh
- scripts/post_build.sh
- scripts/pre_build.sh
Initial Creation of:
- ECR repository
- Code Pipeline
- Infrastructure build configuration
This work is required for the deployment of the new
LAA-MAAT-court-data-api application
> LAWS-775_initial-AWS-infrastructure

- aws/application/application.template
Minor fix to Environment parameter format
> initial-AWS-infrastructure-FIX

- maat-court-data-api/Dockerfile
- maat-court-data-api/build.gradle
Added actuator for health check , to be used by Load balancer.
Expose port 8090 on docker.
> Added actuator for ELB health check

- aws/application/application.template
Increase Load Balancer timeout
This is required as the application is not stablizing using the existing
settings
> LAWS-823-Alter-Load-Balancer-Timeout

- maat-court-data-api/Dockerfile
- maat-court-data-api/src/main/java/gov/uk/courtdata/exception/GlobalAppLoggingHandler.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/service/HearingResultedListener.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laaStatus/service/CourtDataApiClient.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laaStatus/service/LaaStatusPublisher.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/service/CreateLinkListener.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/service/CreateLinkService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/unlink/processor/UnLinkProcessor.java
[Link to story](https://dsdmoj.atlassian.net/browse/CACP-279)
> logging traceability - optimised code and tidy up

- maat-court-data-api/src/main/java/gov/uk/courtdata/exception/GlobalAppLoggingHandler.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laaStatus/controller/LaaStatusCDAController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laaStatus/controller/LaaStatusUpdateController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laaStatus/impl/LaaStatusUpdateImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laaStatus/service/CourtDataApiClient.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laaStatus/service/LaaStatusListener.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laaStatus/service/LaaStatusPublisher.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/LaaTransactionLogging.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/util/LaaTransactionLoggingBuilder.java
[Link to story](https://dsdmoj.atlassian.net/browse/CACP-279)
> added ex trace for logging

- maat-court-data-api/src/main/java/gov/uk/courtdata/laaStatus/service/LaaStatusListener.java
- maat-court-data-api/src/main/resources/application.yaml
Switching ON Liquibase DB Migration Feature.  
Turned on Liquibase application.yaml in order to apply DB changes. 
- [x ] Github should not be reporting conflicts; you should have recently run `git rebase master`.
> Turning ON Liquibase DB Migrations

- maat-court-data-api/src/main/resources/application.yaml
> Disable Liquibase

- maat-court-data-api/src/main/java/gov/uk/courtdata/constants/CourtDataConstants.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/processor/OffenceInfoProcessor.java
Formatting ASN Seq with 3 digits with leading zeros
ASN Seq should be stored as 3 digits as the existing PL/SQL expects this value in this format.  
- [x ] Tests should be passing: `./gradlew test`
- [x ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [x ] You should have checked that the commit messages say why the change was made.
> Formatting ASN Seq with 3 digits with leading zeros

- maat-court-data-api/src/main/java/gov/uk/courtdata/link/service/CreateLinkService.java
Combining Offence & Results Ref Data Processing
Refactoring
> Combining Offence & Results Processing

- maat-court-data-api/src/main/java/gov/uk/courtdata/link/processor/ResultsInfoProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/service/CreateLinkService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/processor/OffenceCodesProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/processor/ResultCodesProcessor.java
Added Null Check to address Non Resulted Hearings
> Added Null Check to address Non Resulted Hearings

- maat-court-data-api/src/main/resources/logback.xml
- maat-court-data-api/src/main/resources/sentry.properties
added extra config to the stack trace. 
- [x ] Tests should be passing: `./gradlew test`
- [x ] Github should not be reporting conflicts; you should have recently run `git rebase master`.
> sentry added stack-trace packages

- maat-court-data-api/src/main/java/gov/uk/courtdata/link/validator/CPDataValidator.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/link/validator/CPDataValidatorTest.java
> Removing Case URN Validation

- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/impl/HearingResultedImpl.java
Processing Result code outside of Crown Court specific processing. 
> Result Code Fix for Crown Court

- .gitattributes
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/service/HearingResultedService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/processor/WqLinkRegisterProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/service/CreateLinkService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/LaaTransactionLogging.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/unlink/controller/UnLinkController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/unlink/validator/UnLinkValidationProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/unlink/validator/UserIdValidator.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/util/LaaTransactionLoggingBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestEntityDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/service/HearingResultedListenerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/service/HearingResultedServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integrationTest/link/controller/LinkControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integrationTest/link/impl/SaveAndLinkImplIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integrationTest/link/service/CreateLinkListenerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integrationTest/unlink/controller/UnLinkControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integrationTest/unlink/impl/UnLinkImplIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integrationTest/unlink/service/UnlinkListenerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/laaStatus/service/LaaStatusPublisherTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/link/service/CreateLinkListenerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/link/service/CreateLinkServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/unlink/validator/ReasonValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/unlink/validator/UnLinkValidationProcessorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/unlink/validator/UserIdValidatorTest.java
Code Improvement 
Adding Tests
> Refactoring Changes

- aws/application/parameters/development-maat-cd-api-pipeline.json
- aws/application/parameters/production-maat-cd-api-pipeline.json
- aws/application/parameters/staging-maat-cd-api-pipeline.json
- aws/application/parameters/test-maat-cd-api-pipeline.json
- aws/application/parameters/uat-maat-cd-api-pipeline.json
Production release related changes
https://dsdmoj.atlassian.net/browse/CACP-396
Cloud infrastructure prod resources created.
Prod pipeline params configured.
CDA uri and prod credentials created and updated.
> Add production pipeline param values and updated cda uris across envs.

- maat-court-data-api/src/test/java/gov/uk/courtdata/integrationTest/link/controller/LinkControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integrationTest/link/impl/SaveAndLinkImplIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integrationTest/link/service/CreateLinkListenerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integrationTest/unlink/impl/UnLinkImplIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integrationTest/unlink/service/UnlinkListenerTest.java
Refactor integration test.
Clear up repos before test.
> Refactor integration tests to clean up repos before test run

- maat-court-data-api/src/test/java/gov/uk/courtdata/integrationTest/link/service/CreateLinkListenerIntegrationTest.java
> Add cleanup repos on link integration

- maat-court-data-api/src/test/java/gov/uk/courtdata/integrationTest/link/impl/SaveAndLinkImplIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integrationTest/link/service/CreateLinkListenerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integrationTest/unlink/impl/UnLinkImplIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integrationTest/unlink/service/UnlinkListenerTest.java
> Updating Int Test

- maat-court-data-api/build.gradle
- maat-court-data-api/src/main/java/gov/uk/courtdata/exception/GlobalAppLoggingHandler.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/controller/LaaStatusUpdateController.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/enums/IOJDecisionTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/enums/LAAStatusTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/enums/WQTypeTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/service/CrownCourtHearingServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/laastatus/controller/LaaStatusUpdateControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/laastatus/validator/LaaStatusValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/link/processor/CaseInfoProcessorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/link/processor/ResultsInfoProcessorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/link/processor/SessionInfoProcessorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/processor/OffenceCodeRefDataProcessorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/unlink/validator/UnLinkValidationProcessorTest.java
UnitTest Case Updates to cover Edge cases
> Refactoring + Unit Test case Update

- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/CrownCourtCode.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/impl/CrownCourtProcessingImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/validator/OUCodeValidator.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/hearing/CCOutComeData.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/CrownCourtCodeRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/impl/CrownCourtProcessingImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/validator/AppealTypeValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/validator/CrownCourtOutComesValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/validator/OUCodeValidatorTest.java
https://dsdmoj.atlassian.net/browse/CACP-389
Implemented Look Up logic to translate Crown Code Value from OU code
> Crown Court Code Look Up from OU Code

- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/impl/CrownCourtProcessingImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/validator/CrownCourtValidationProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/validator/OUCodeValidator.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/hearing/CCOutComeData.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/impl/CrownCourtProcessingImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/validator/CrownCourtValidationProcessorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/validator/OUCodeValidatorTest.java
https://dsdmoj.atlassian.net/browse/CACP-389
As agreed with CDA, We will be fetching OU Code from Session as Opposed to CCOutCome.
> Fetching OU Code from Session as Opposed to CCOutCome

- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/validator/CrownCourtValidationProcessor.java
> Fixing log info

- .github/CODEOWNERS
- .github/dependabot.yml
Enabling Dependent bot for Security Updates and PR for Versions Updates. 
> Enabling Dependentbot

- .github/dependabot.yml
> Fixing Dependantbot config

- aws/application/application.template
- aws/application/parameters/development-maat-cd-api-pipeline.json
- aws/application/parameters/production-maat-cd-api-pipeline.json
- aws/application/parameters/staging-maat-cd-api-pipeline.json
- aws/application/parameters/test-maat-cd-api-pipeline.json
- aws/application/parameters/uat-maat-cd-api-pipeline.json
Jira [LAWS-976](https://dsdmoj.atlassian.net/browse/LAWS-976)
- Install API Gateway interface in development with Cognito Authoriser
This work is required to allow secure access from external
applications
> LAWS-976-Add-Api-Gateway-to-development

- aws/application/application.template
Jira [LAWS-976](https://dsdmoj.atlassian.net/browse/LAWS-976)
- Fix Cloudformation condition template error
This work is required to allow secure access from external
applications
> LAWS-976-fix-Cloudformation-condition-issue

- maat-court-data-api/src/main/java/gov/uk/courtdata/model/laastatus/LaaStatusUpdate.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/service/HearingDTOMapperTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/laastatus/builder/CourtDataDTOBuilderTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/laastatus/builder/RepOrderUpdateMessageBuilderTest.java
Missing unit test cases for laasstatusupdate. For builder classes. 
> Added unit test cases for LaaStatusUpdate.

- maat-court-data-api/build.gradle
https://dsdmoj.atlassian.net/browse/CACP-419
- Enabled BOM on gradle file
- Moved all dependency versions into a centralised extension. 
> Enabling BOM, Centralising Versions

- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/builder/RepOrderUpdateMessageBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/laastatus/builder/RepOrderUpdateMessageBuilderTest.java
- Added solicitor organisation and contact details back to laa status update request.
> Laa status solicitor update

- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/CaseEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/DefendantEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/OffenceEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/ProceedingEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/ResultEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/SessionEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/SolicitorEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/WQCaseEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/processor/ResultsInfoProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/service/CreateLinkListener.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/id/AsnSeqTxnCaseId.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/id/CaseTxnId.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/id/ProceedingMaatId.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/CaseRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/DefendantRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/OffenceRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/ProceedingRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/ResultRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/SessionRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/SolicitorRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/WQCaseRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/impl/SaveAndLinkImplIntegrationTest.java
https://dsdmoj.atlassian.net/browse/CACP-444
Corrected Entities and Repos use the Composite key that is available on DB table.
> Correcting Entities and Repos to Use Correct ID/Key

- maat-court-data-api/src/main/resources/sentry.properties
[Link to story](https://dsdmoj.atlassian.net/browse/CACP-393)
We have a got a new Sentry system and update the DSN value in the property file 
> Updated sentry properties file for new sentry system config

- aws/application/application.template
Adding Post MVP flag on App Template. 
> Adding Post MVP flag on App Template

- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/builder/CourtDataDTOBuilder.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/OffenceRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/laastatus/builder/CourtDataDTOBuilderTest.java
https://dsdmoj.atlassian.net/browse/CACP-469
Fix to get the latest offence id the offence on laa status update.
> Uat laa status fix

- aws/application/application.template
> Formatting YAML

- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/processor/WQOffenceProcessor.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/processor/WQOffenceProcessorTest.java
https://dsdmoj.atlassian.net/browse/CACP-478
Apply left padding to asn seq on hearing.
> Apply left padding on ASN Seq

- aws/application/application.template
Jira [LAWS-1162](https://dsdmoj.atlassian.net/browse/LAWS-1162)
- Add new Cognito Client-App for CDA
- Add new Client-App to maat-cd-api authorizer
This work is required to onboard CDA for maat-cd-api
> LAWS-1162-Onboard-new-api-client-for-maat-cd-api

- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/impl/CrownCourtProcessHelper.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/impl/CrownCourtProcessHelperTest.java
https://dsdmoj.atlassian.net/browse/CACP-448
- Add validation to evaluate bench warrant flag only for trials.
> Add validation to set benchwarrant only for trials

- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/WQOffenceEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/dto/OffenceDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/processor/WQOffenceProcessor.java
https://dsdmoj.atlassian.net/browse/CACP-486
Laa status update requires offenceId and it is added into hearing wq.
> Add offenceid to hearing wq pocessing

- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/CrownCourtStoredProcedureRepository.java
Making Appeal Type as Nullable for the procedure call
> Making Appeal Type as Nullable

- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/CrownCourtCaseType.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/enums/CrownCourtCaseTypeTest.java
Adding Either way for Trial Outcomes
> Adding Either way for Trial Outcomes

- aws/application/parameters/production-maat-cd-api-pipeline.json
> Updating Prod CDA URL

- scripts/build.sh
Added missing property scm provider for sonarqube.
https://dsdmoj.atlassian.net/browse/CACP-509
> sonarqube - added git as scm provider

- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/MessageType.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/QueueMessageType.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/service/HearingResultedListener.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/client/CourtDataAdapterClient.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/service/LaaStatusJobListener.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/service/LaaStatusListener.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/service/CreateLinkCpJobStatusListener.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/service/CreateLinkListener.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/service/QueueMessageLogService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/unlink/service/UnlinkListener.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/service/HearingResultedListenerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/laastatus/service/CpJobStatusListenerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/link/service/CreateLinkCpJobStatusListenerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/link/service/CreateLinkListenerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/service/QueueMessageLogServiceTest.java
Log outbound requests to CDA/HMCTS
https://dsdmoj.atlassian.net/browse/CACP-519
Log HTTP requests for laa status update .
> Log outbound request payload

- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/WqLinkRegisterEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/unlink/impl/UnLinkImpl.java
Modify unlink removed date
https://dsdmoj.atlassian.net/browse/CACP-522
Change unlink removed date to datetime in consistent with libra.
> change unlink remove date to datetime

- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/processor/WQCoreProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/processor/WqCoreInfoProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/processor/WqLinkRegisterProcessor.java
Code tidy up.
https://dsdmoj.atlassian.net/browse/CACP-522
Sonar code smell and tidy up.
> CACP-522 code tidyup

- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/LoggingData.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/exception/GlobalAppLoggingHandler.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/controller/LaaStatusUpdateController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/service/LaaStatusListener.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/controller/LinkController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/unlink/controller/UnLinkController.java
- maat-court-data-api/src/main/resources/logback.xml
when making calls to rest API, the tx-id and maat-is not being setup. This created a problem with the logging missing the meta-data. 
> Logging message with maat and tx-id

- maat-court-data-api/src/main/java/gov/uk/courtdata/link/validator/CPDataValidator.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/validator/LinkExistsValidator.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/validator/MaatIdValidator.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/controller/LinkControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/link/validator/CPDataValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/link/validator/LinkExistsValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/validator/MaatIdValidatorTest.java
Validation API error messages 
https://dsdmoj.atlassian.net/browse/LASB-409
Validation messages generated on API are propagated up to VCD, messages are now business friendly. 
> LASB-409 Update validation api messages

- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/impl/CrownCourtProcessHelper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/service/CrownCourtHearingService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/XLATResultRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/impl/CrownCourtProcessHelperTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/service/CrownCourtHearingServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-403)
Calculate the crown court outcome. 
> LASB - 403 Calculate Crown court outcome when case is concluded .

- aws/application/application.template
Enable api gateway to further environments
https://dsdmoj.atlassian.net/browse/LASB-409
Allow api gateway to promoted in other environments
> enable api gateway to envs other than  prod

- aws/application/application.template
Jira - [LAWS-1313](https://dsdmoj.atlassian.net/browse/LAWS-1313)
- Fix a Cognito Domain name issue that prevents the stack from being
deployed to multiple environments
This change is required to allow releases to environments other that
development.
> LAWS-1313-Fix-cognito-domain-name-issue

- aws/application/application.template
- aws/application/parameters/development-maat-cd-api-pipeline.json
- aws/application/parameters/production-maat-cd-api-pipeline.json
- aws/application/parameters/staging-maat-cd-api-pipeline.json
- aws/application/parameters/test-maat-cd-api-pipeline.json
- aws/application/parameters/uat-maat-cd-api-pipeline.json
Cognito domain name refactor
https://dsdmoj.atlassian.net/browse/LASB-409
Refactor to generate cognito domain urls with short environment names.
> Refactor to use cognito domain with short environment names

- aws/application/application.template
- maat-court-data-api/build.gradle
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/unlink/service/UnlinkListenerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/laastatus/controller/LaaStatusUpdateControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/unlink/controller/UnLinkControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/unlink/impl/UnLinkImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/unlink/service/UnlinkListenerTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-445)
The condition has been removed for an API endpoint. This condition was introduced to hide some of the API from the production environment.
> Feature/lasb 445 

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-445)
To deploy the API endpoint and its API gateway access. 
> Update the AWS template to remove the condition

- maat-court-data-api/build.gradle
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/impl/HearingResultedImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/processor/WQCaseProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/service/HearingResultedPublisher.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/service/HearingResultedService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/service/CrownCourtHearingServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/validator/OUCodeValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/impl/HearingResultedImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/processor/WQCaseProcessorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/processor/WQOffenceProcessorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/service/HearingResultedPublisherTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/lasb-428)
Added test coverage for the hearing module. 
> Added mutation (PIT) testing coverage for hearing.

- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/impl/HearingResultedImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/processor/OffenceInfoProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/unlink/validator/ReasonValidator.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/enums/IOJDecisionTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/enums/LAAStatusTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/enums/WQTypeTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/validator/CaseTypeValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/validator/OUCodeValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/processor/WQCaseProcessorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/job/QueueMessageMaintenanceJobTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/laastatus/validator/LaaStatusValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/link/processor/RepOrderInfoProcessorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/unlink/impl/UnLinkImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/validator/MaatIdValidatorTest.java
> Fixing tech debt

- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/PleaEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/VerdictEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/PleaTrialOutcome.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/VerdictTrialOutcome.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/impl/CrownCourtProcessHelper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/impl/CrownCourtProcessingImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/impl/OffenceHelper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/service/CrownCourtHearingService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/validator/CaseTypeValidator.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/validator/CrownCourtOutComesValidator.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/validator/CrownCourtValidationProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/dto/VerdictDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/processor/VerdictProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/Verdict.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/hearing/CCOutComeData.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/OffenceRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/PleaRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/VerdictRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/util/IntegerUtil.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/impl/CrownCourtProcessHelperTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/impl/CrownCourtProcessingImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/impl/OffenceHelperTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/service/CrownCourtHearingServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/validator/AppealTypeValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/validator/CaseTypeValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/validator/CrownCourtOutComesValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/validator/CrownCourtValidationProcessorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/service/HearingDTOMapperTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/lasb-534)
Implementation to calculate crown court outcome using plea and verdict data. Once calculated then persist this information to the table using the stored procedure.  This is still a wip. 
> Implementation to calculate crown court outcome

- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/OffenceRepository.java
> Correcting Rebase issue

- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/service/CrownCourtHearingService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/processor/CourtApplicationsPreProcessor.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/processor/CourtApplicationsPreProcessorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/processor/WQOffenceProcessorTest.java
> Fixing Sonar Bugs

- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/OffenceRepository.java
> Native Query Update

- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/ApplicationClassification.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/ModeOfTrial.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/processor/CourtApplicationsPreProcessor.java
Setting Court Application Defaults. 
> Setting Court Application Defaults

- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/service/CrownCourtHearingService.java
Updated the CC outcome for the existing cases.
> Updated the CC outcome for the existing cases.

- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/service/CrownCourtHearingService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/service/CrownCourtHearingServiceTest.java
Updated CC hearing service to handle edge and null value cases for cc outcome value. 
> Updated cc outcome to handle some edge case and when its null values.

- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/MessageType.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/controller/LaaStatusUpdateController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/service/LaaStatusServiceUpdate.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/laastatus/controller/LaaStatusUpdateControllerTest.java
To fix the laa status posting multiple request to CDA.
> For LAA Status removing SQS implementation and posting CDA.

- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/builder/CourtDataDTOBuilder.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/controller/LaaStatusUpdateController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/service/LaaStatusServiceUpdate.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/laastatus/controller/LaaStatusUpdateControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/laastatus/service/LaaStatusServiceUpdateTest.java
Added test file for code coverage. 
> Added test class for laa status service update.

- maat-court-data-api/build.gradle
- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/LoggingData.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/exception/GlobalAppLoggingHandler.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/service/HearingResultedListener.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/client/CourtDataAdapterClient.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/service/LaaStatusPublisher.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/controller/LinkController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/service/CreateLinkListener.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/unlink/service/UnlinkListener.java
…oud watch logs
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-620)
Upgraded Sentry version from 3x to 5x. Added more meta-data for both Sentry and for cloud watch logs. 
> Upgraded sentry version to 5x. Added more meta-data for error

- maat-court-data-api/src/main/java/gov/uk/courtdata/jms/JmsConfig.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-640)
Updated the JMS config from Client Acknowledgement to Auto Acknowledgement. 
> Updating the JMS config from client ack to auto ack.

- aws/application/parameters/development-maat-cd-api-pipeline.json
- maat-court-data-api/gradle/wrapper/gradle-wrapper.properties
> Set post MVP flag to false for unused SQS

- maat-court-data-api/build.gradle
> Reverting SQ version

- maat-court-data-api/src/main/java/gov/uk/courtdata/jms/JmsConfig.java
> Fixing Build Failiures

- aws/application/application.template
> Updating Container Health End Point

- aws/application/application.template
> Fixing pLaaProsecutionConcludedQueue

- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/impl/CrownCourtProcessHelper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/impl/CrownCourtProcessingImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/service/CrownCourtHearingService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/validator/CaseTypeValidator.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/validator/CrownCourtOutComesValidator.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/hearing/CCOutComeData.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/impl/CrownCourtProcessHelperTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/impl/CrownCourtProcessingImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/service/CrownCourtHearingServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/validator/AppealTypeValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/validator/CaseTypeValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/validator/CrownCourtOutComesValidatorTest.java
https://dsdmoj.atlassian.net/browse/LASB-737
> Fixing Data Contract of CC Outcome field

- aws/application/parameters/production-maat-cd-api-pipeline.json
- aws/application/parameters/staging-maat-cd-api-pipeline.json
- aws/application/parameters/uat-maat-cd-api-pipeline.json
Fixed the SQS name typo fixed. Changed the SQS name from underscore (_) to dash (-) Different naming configuration than the terraform CP. 
> Fixed the SQS name typo fixed.

- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/service/CrownCourtHearingService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/crowncourt/service/CrownCourtHearingServiceTest.java
Triggering CC Outcome Processing when all offenses have verdict data & CC Outcome is present. 
> Fixing CC OutCome Fix

- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/crowncourt/service/CrownCourtHearingService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/service/ProsecutionConcludedListener.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/prosecutionconcluded/ProsecutionConcludedListenerTest.java
Added   a Temp Change to Data Fix CC outcomes 
> Adding a temp change to data fix CC Outcomes

- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/impl/FinancialAssessmentImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/mapper/FinancialAssessmentDTOMapper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/service/FinancialAssessmentService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/validator/CreateAssessmentValidator.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/validator/FinancialAssessmentValidationProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/validator/UpdateAssessmentValidator.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/FinancialAssessmentDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/FinancialAssessmentEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/HardshipReviewEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/PassportAssessmentEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/FinancialAssessmentType.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/assessment/CreateFinancialAssessment.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/assessment/FinancialAssessment.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/assessment/UpdateFinancialAssessment.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/FinancialAssessmentRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/HardshipReviewRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/PassportAssessmentRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/util/DateUtil.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/validator/FinancialAssessmentIdValidator.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/impl/FinancialAssessmentImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/service/FinancialAssessmentServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/validator/CreateAssessmentValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/validator/FinancialAssessmentValidationProcessorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/validator/UpdateAssessmentValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestEntityDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/validator/FinancialAssessmentIdValidatorTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-740)
Creation of new endpoints to support CRUD operations on the financial_assessments table.
> CRUD endpoints for interacting with financial_assessments table

- maat-court-data-api/src/main/resources/schema/apiCreateInitialMeansAssessment.json
- maat-court-data-api/src/main/resources/schema/assessment/apiInitialMeansAssessment.json
- maat-court-data-api/src/main/resources/schema/common/apiAssessmentDetail.json
- maat-court-data-api/src/main/resources/schema/common/apiAssessmentStatus.json
- maat-court-data-api/src/main/resources/schema/common/apiFrequency.json
- maat-court-data-api/src/main/resources/schema/common/apiNewWorkReason.json
- maat-court-data-api/src/main/resources/schema/common/apiReviewType.json
https://dsdmoj.atlassian.net/browse/LASB-775
Schema Creation for the Initial Means Assessment processing. 
> Adding schema for the initial means assessment processing

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/codeql-analysis.yml
- aws/pipeline/parameters/maat-cd-api-deployment-pipeline-shared-services.json
https://github.com/ministryofjustice/laa-maat-court-data-api/issues/412
Updating default branch from Master to Main
> Updating default branch from Master to Main

- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/listner/request/ProsecutionConcluded.java
[Link to story](https://dsdmoj.atlassian.net/browse/lasb-856)
> Changing the data-type for defendant-id from integer to UUID.

- maat-court-data-api/build.gradle
> reverting dependant bot updates

- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/model/ProsecutionConcluded.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/prosecutionconcluded/helper/CalculateOutcomeHelperTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/prosecutionconcluded/impl/ProsecutionConcludedImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/prosecutionconcluded/service/ProsecutionConcludedServiceTest.java
renaming ProsecutionConcluded as per CDA contract 
> renaming ProsecutionConcluded as per CDA contract

- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/PassportAssessmentRepository.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-866)
Updated column names to match those used in the database.
> Fix for incorrect column name in repository causing database exception

- maat-court-data-api/src/main/java/gov/uk/courtdata/exception/GlobalAppLoggingHandler.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/exception/HearingNotAvailableException.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/LaaTransactionLogging.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/Metadata.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/model/ProsecutionConcluded.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/service/ProsecutionConcludedService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/publisher/AwsStandardSqsPublisher.java
> Set a max limit on the republishing messages to the SQS for CC

- maat-court-data-api/src/main/java/gov/uk/courtdata/publisher/AwsStandardSqsPublisher.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/QueueMessageLogRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/service/QueueMessageLogService.java
> Fixing the sqs messages publishing multiple time.

- maat-court-data-api/src/main/java/gov/uk/courtdata/constants/CourtDataConstants.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/OffenceEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/WQOffenceEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/WQResultEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/WqCoreEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/WQType.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/impl/HearingResultedImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/processor/WQCoreProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/processor/WQOffenceProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/processor/WQResultProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/helper/OffenceHelper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/service/ProsecutionConcludedService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/publisher/AwsStandardSqsPublisher.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/OffenceRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/WQOffenceRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/enums/WQTypeTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/impl/HearingResultedImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/prosecutionconcluded/helper/OffenceHelperTest.java
https://dsdmoj.atlassian.net/browse/LASB-888
> Including Additional Business rules for CC Outcome

- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/ProsecutionConcludedEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/CaseConclusionStatus.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/model/ProsecutionConcluded.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/service/ProsecutionConcludedDataService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/service/ProsecutionConcludedService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/service/prosecutionConcludedSchedulerService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/ProsecutionConcludedRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/prosecutionconcluded/service/ProsecutionConcludedServiceTest.java
https://dsdmoj.atlassian.net/browse/LASB-888
> Delaying PC messages processing

- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/helper/OffenceHelper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/service/ProsecutionConcludedService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/prosecutionconcluded/helper/OffenceHelperTest.java
> Fixing the issue with Case ID

- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/builder/CaseConclusionDTOBuilder.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/service/prosecutionConcludedSchedulerService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/ProsecutionConcludedRepository.java
> Processing MAGS Outcome + Fixing NPE

- maat-court-data-api/src/test/java/gov/uk/courtdata/prosecutionconcluded/service/prosecutionConcludedSchedulerServiceTest.java
> fixing the build issue

- aws/application/application.template
Regarding LAWS-2198 and LAWS-2199, this PR adds additional API Gateway and Cognito resources to existing MAAT API infrastructure. Namely, we are adding a new API route and new User Pool Client for the new Crime Means Assessment application.
> Crime Means Assessment - Add API GW Route + Cognito User Pool Client

- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/controller/PassportAssessmentController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/impl/PassportAssessmentImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/service/PassportAssessmentService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/controller/HardshipReviewController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/impl/HardshipReviewImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/service/HardshipReviewService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/iojAppeal/controller/IOJAppealController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/iojAppeal/impl/IOJAppealImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/iojAppeal/service/IOJAppealService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/HardshipReviewRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/IOJAppealRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/PassportAssessmentRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/controller/PassportAssessmentControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/impl/PassportAssessmentImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/service/PassportAssessmentServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hardship/controller/HardshipReviewControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hardship/impl/HardshipReviewImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hardship/service/HardshipReviewServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/iojAppeal/controller/IOJAppealControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/iojAppeal/impl/IOJAppealImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/iojAppeal/service/IOJAppealServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-970)
- added endpoints to retrieve passport, hardship and iojappeal assessments
- added unit test and controller test
> Lasb 970 update controllers findby rep

- maat-court-data-api/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1019)
> LASB-1019: Updating spring boot  version to 5.3.18

- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/controller/PassportAssessmentController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/authorization/controller/AuthorizationController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/controller/HardshipReviewController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/iojAppeal/controller/IOJAppealController.java
- maat-court-data-api/src/main/resources/application.yaml
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/controller/PassportAssessmentControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/authorization/controller/AuthorizationControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hardship/controller/HardshipReviewControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/iojAppeal/controller/IOJAppealControllerTest.java
- maat-court-data-api/src/test/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1011)
> LASB-1011 - Updated assessment API domain

- maat-court-data-api/src/main/resources/application.yaml
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/controller/PassportAssessmentControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/authorization/controller/AuthorizationControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hardship/controller/HardshipReviewControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/iojAppeal/controller/IOJAppealControllerTest.java
- maat-court-data-api/src/test/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1011)
> LASB-1011: Corrected the assessment api endpoint domain.

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1011)
> LASB-1011: Updated the api gateway configuration

- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/impl/ChildWeightHistoryImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/impl/ChildWeightingsImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/impl/FinancialAssessmentDetailsHistoryImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/impl/FinancialAssessmentDetailsImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/impl/FinancialAssessmentHistoryImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/impl/FinancialAssessmentImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/impl/RepOrderImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/mapper/FinancialAssessmentHistoryMapper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/service/FinancialAssessmentHistoryService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/ChildWeightHistoryDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/FinancialAssessmentDetailsHistoryDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/FinancialAssessmentsHistoryDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/ChildWeightHistoryEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/FinancialAssessmentDetailsHistoryEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/FinancialAssessmentsHistoryEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/RepOrderEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/Frequency.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/HardshipReviewStatus.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/impl/ChildWeightHistoryImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/impl/FinancialAssessmentDetailsHistoryImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/impl/FinancialAssessmentHistoryImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/service/FinancialAssessmentHistoryServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestEntityDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/impl/SaveAndLinkImplIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/service/CreateLinkListenerIntegrationTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1015)
- added controller endpoint, service, impl, mapper, dtos for createAssesmentHistory
- unit tests
- updated entities as required
> Lasb 1015 controller service create assessment hist

- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/PleaTrialOutcome.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/enums/PleaTrialOutcomeTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1044)
> LASB 1044 - Crown court plea mapping error

- aws/application/application.template
Enables container insights for the ECS cluster.
> Enables container insights for the ECS cluster.

- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/OffenceEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/OffenceRepository.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1056)
Updated queries in the OffenceRepository, improving performance by as much as 10x.
> Improved performance of queries run on the XXMLA_OFFENCE table

- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/helper/CalculateOutcomeHelper.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/prosecutionconcluded/helper/CalculateOutcomeHelperTest.java
> LASB-1053 Suppress Exception

- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/FinancialAssessmentRepository.java
…pository.
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1072)
> LASB-1072: Added reference to TOGDATA in the Financial assessments repository

- maat-court-data-api/src/main/resources/application.yaml
- maat-court-data-api/src/main/resources/logback.xml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1093)
Fixed Sentry Logback misconfiguration issue. This should remove the errors present on start up and speed up application launch times. It will also mean that the Sentry specific settings in the `application.yaml` are correctly detected and applied.
> LASB-1093 Fixed Sentry Logback misconfiguration

- maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/service/HearingResultedListener.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/jms/JmsConfig.java
> Reduce-Concurrent-Consumers

- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/impl/FinancialAssessmentImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/service/FinancialAssessmentService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/FinancialAssessmentRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/impl/FinancialAssessmentImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/service/FinancialAssessmentServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1105)
Ensure old assessment are replaced when a new one is created.
> LASB-1105: Ensure old assessment are replaced when a new one is created

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-999)
> LASB-999 - Missing application parameters for actuator metrics changes added.

- aws/application/application.template
- aws/application/parameters/development-maat-cd-api-pipeline.json
- aws/application/parameters/production-maat-cd-api-pipeline.json
- aws/application/parameters/staging-maat-cd-api-pipeline.json
- aws/application/parameters/test-maat-cd-api-pipeline.json
- aws/application/parameters/uat-maat-cd-api-pipeline.json
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-999)
> LASB-999 - Application template changes

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-999)
> LASB-999 - Add metrics role

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-998)
Updated Daemon address to default as the application is being run under Fargate.
> Use Default Daemon Address

- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/config/AWSXRayConfig.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/ChildWeightHistoryEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/ChildWeightingsEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/FinancialAssessmentDetailEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/FinancialAssessmentDetailsHistoryEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/FinancialAssessmentEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/FinancialAssessmentsHistoryEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/HardshipReviewDetailEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/HardshipReviewEntity.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-998)
Fixes problems encountered during json serialisation when the x-ray transmits trace segments.
> Fix back Reference Infinite Recursion During JSON Serialisation

- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/MockCdaWebConfig.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/laastatus/service/LaaStatusUpdateControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/util/MockMvcIntegrationTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1045)
> LASB-1145: Update Laa Status Update integration test to use MockMVC

- aws/application/application.template
> Added missing variable for PP Queue

- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/controller/PostProcessingController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/service/MeansAssessmentPostProcessingListener.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/service/PostProcessingService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/assessment/PostProcessing.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/PostProcessingStoredProcedureRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/controller/PostProcessingControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/service/MeansAssessmentPostProcessingListenerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/service/PostProcessingAssessmentServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-93)
Pass user session details to the Post processing stored procedure.
> LCAM-93|Pass user session details to the Post processing stored proc

- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/FinancialAssessmentEntity.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-110)
> LCAM-110 - Post processing parameter error

- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/FinancialAssessmentDetailsHistoryDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/assessment/FinancialAssessmentDetails.java
- maat-court-data-api/src/main/resources/schema/common/apiAssessmentDetail.json
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/assessment/FinancialAssessmentControllerIntegrationTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-154)
Add id field to the AssessmentDetails object in line with DB
> LCAM-154|Add id field to the AssessmentDetails object in line with DB

- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/impl/RepOrderImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/service/RepOrdersService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/validator/FinancialAssessmentValidationProcessor.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/validator/UpdateAppDateCompletedValidator.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/RepOrderEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/assessment/UpdateAppDateCompleted.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/RepOrderRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/impl/RepOrderImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/service/RepOrdersServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/validator/FinancialAssessmentValidationProcessorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/validator/UpdateAppDateCompletedValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/assessment/FinancialAssessmentControllerIntegrationTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-54)
> LCAM-54-New API for update app date completed'

- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/MockCdaWebConfig.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1287)
> LASB-1287: Corrected usage of the CDA base url during integration tests.

- maat-court-data-api/src/main/java/gov/uk/courtdata/model/assessment/ChildWeightings.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/assessment/FinancialAssessmentControllerIntegrationTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-191)
Adding Id to the ChildWeighting object.
> LCAM-191|Adding Id to the ChildWeighting object

- maat-court-data-api/src/main/java/gov/uk/courtdata/model/assessment/FinancialAssessmentDetails.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/assessment/FinancialAssessmentControllerIntegrationTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-134)
> LCAM-134-added dateModified

- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/FinancialAssessmentDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/FinancialAssessmentEntity.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestEntityDataBuilder.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-61)
> LCAM-61-Added new Entity field

- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/CaseConclusionStatus.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/service/ProsecutionConcludedService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/service/prosecutionConcludedScheduler.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/WQOffenceRepository.java
[
[[Link to story](https://dsdmoj.atlassian.net/browse/AP-XXX)](https://dsdmoj.atlassian.net/browse/LASB-1400)](https://dsdmoj.atlassian.net/browse/LASB-1400)
> Fixing the table Name

- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/hardship/HardshipControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/laastatus/service/LaaStatusUpdateControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/controller/LinkControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/impl/SaveAndLinkImplIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/service/CreateLinkListenerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/prosecution_concluded/ProsecutionConcludedIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/repOrder/RepOrderControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/unlink/service/UnlinkListenerTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1400)
> Fix build issues

- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/FinancialAssessmentDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/FinancialAssessmentEntity.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestEntityDataBuilder.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-61)
> LCAM-61-added entity field

- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/prosecution_concluded/ProsecutionConcludedAndHearingIntegrationTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/lasb-1288)
> Lasb 1288 int test

- aws/application/application.template
> Added CCP Cognito User Pool

- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/CorrespondenceEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/CorrespondenceRepository.java
> LCAM-287-Added Entity and repository

- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/ContributionsEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/ContributionsRepository.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-286)
Add Entity and Repository classes for Contributions.
> LCAM-286|Add Entity and Repository classes for Contributions

- maat-court-data-api/src/main/java/gov/uk/courtdata/iojAppeal/impl/IOJAppealImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/IOJAppealRepository.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-221)
Replace the native query.
> LCAM-221|Removing the native queries as per review comments

- maat-court-data-api/src/main/java/gov/uk/courtdata/link/validator/PreConditionsValidator.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/controller/LinkControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/link/validator/PreConditionsValidatorTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/lasb-1510)
Removed the existing link validation when linking maat-id and caseURN. This will allow CDA to process Common Platform request async. 
> Removed the validation for MAAT-id from the rest API call.

- maat-court-data-api/build.gradle
- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/builder/CaseConclusionDTOBuilder.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/helper/CalculateOutcomeHelper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/prosecutionconcluded/service/ProsecutionConcludedScheduler.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/util/SignatureParser.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/prosecutionconcluded/service/ProsecutionConcludedSchedulerTest.java
[LASB-1558](https://dsdmoj.atlassian.net/browse/LASB-1558)
Fixing SonarQube issues 
> LASB-1558 Code changes sonarqube issues

- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/repOrder/RepOrderControllerIntegrationTest.java
[LASB-1616](https://dsdmoj.atlassian.net/browse/LASB-1616)
> LASB-1616 Fix added for test case failure

- maat-court-data-api/src/main/resources/application.yaml
> Added Context

- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/OffenceRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/WQOffenceRepository.java
[LASB-1618](https://dsdmoj.atlassian.net/browse/LASB-1618)
Added application flag to existing queries
> LASB-1618 added application flag

- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/WQLinkRegisterDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/wqlinkregister/controller/WQLinkRegisterController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/wqlinkregister/impl/WQLinkRegisterImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/wqlinkregister/mapper/WQLinkRegisterMapper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/wqlinkregister/service/WQLinkRegisterService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/wqoffence/controller/WQOffenceController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/wqoffence/impl/WQOffenceImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/wqoffence/service/WQOffenceService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestEntityDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/wqlinkregister/WQLinkRegisterControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/wqoffence/WQOffenceControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/wqlinkregister/controller/WQLinkRegisterControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/wqlinkregister/impl/WQLinkRegisterImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/wqlinkregister/service/WQLinkRegisterServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/wqoffence/controller/WQOffenceControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/wqoffence/impl/WQOffenceImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/wqoffence/service/WQOffenceServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-252)
> LCAM-252-Added new endpoint

- maat-court-data-api/src/main/resources/application.yaml
https://dsdmoj.atlassian.net/browse/LASB-1626
> Allow only 5 % of the error to Sentry

- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/WQHearingDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/WQHearingRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/wqhearing/controller/WQHearingController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/wqhearing/impl/WQHearingImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/wqhearing/mapper/WQHearingMapper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/wqhearing/service/WQHearingService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestEntityDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/wqhearing/WQHearingControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/wqhearing/controller/WQHearingControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/wqhearing/impl/WQHearingImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/wqhearing/service/WQHearingServiceTest.java
> LCAM-256-WQ Offence endpoint

- maat-court-data-api/src/main/java/gov/uk/courtdata/controller/CrownCourtController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/UpdateSentenceOrder.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/service/CrownCourtOutcomeService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/controller/CrownCourtControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/service/CrownCourtOutcomeServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-434)
Create endpoints for CrownCourtProcessingRepository.
> LCAM-434|Create endpoints for CrownCourtProcessingRepository

- maat-court-data-api/src/main/java/gov/uk/courtdata/constants/CourtDataConstants.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/controller/CrownCourtController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/controller/ReservationsController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/controller/WQResultController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/controller/XLATResultController.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/controller/ReservationsControllerTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-453)
Create an endpoint to check if a MAAT ID is Locked in the Reservations table.
> LCAM-453|Create an endpoint to check if a MAAT ID is Locked

- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/controller/RepOrderController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/impl/RepOrderImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/service/RepOrderService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/repOrder/RepOrderControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/controller/RepOrderControllerTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-229)
Return RepOrderDTO for update Api
> LCAM-229-Update report endpoint return object. 

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-427)
CCP Cognito user
> LCAM-427-CCP Cognito user 

- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/RepOrderCapitalEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/controller/RepOrderCapitalController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/impl/RepOrderCapitalImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/service/RepOrderCapitalService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/RepOrderCapitalRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestEntityDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/repOrder/RepOrderCapitalIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/controller/RepOrderCapitalControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/impl/RepOrderCapitalImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/service/RepOrderCapitalServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-470)
New endpoint added for CALC_EVIDENCE_FEE
> LCAM-470-New endpoint

- maat-court-data-api/src/test/resources/application.yaml
> Added support for spring cloud for testing.

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-495)
Adding Cognito for crime evidence service
> LCAM-495-Add crime evidence

- README.md
Updated cloud platform setup section of readme as I was working through it to clarify a few points and correct a typo or two.
> clarified few points in cloud platform setup of readme

- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/controller/RepOrderController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/impl/RepOrderImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/service/RepOrderService.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-533)
Return modified date time after updating the date completed field on the RepOrders table.
> LCAM-533|Return modified date time

- aws/pipeline/maat-cd-api-deployment-pipeline.template
[LASB-1757](https://dsdmoj.atlassian.net/browse/LASB-1757)
> [LASB-1757] updated aws codebuild standard version to 6.0

- buildspec-lz.yml
> [LASB-1757] changed openjdk11 to corretto11

- buildspec-lz.yml
> [LASB-1757] removed docker runtime version

- aws/pipeline/maat-cd-api-deployment-pipeline.template
- buildspec-lz.yml
> [LASB-1757] reverting code build upgrade changes

- aws/pipeline/maat-cd-api-deployment-pipeline.template
- buildspec-lz.yml
- scripts/pre_build.sh
[LASB-1757](https://dsdmoj.atlassian.net/browse/LASB-1757)
[LASB-1757]: https://dsdmoj.atlassian.net/browse/LASB-1757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LASB-1757] updating codebuild version

- aws/pipeline/maat-cd-api-deployment-pipeline.template
- scripts/pre_build.sh
> [LASB-1757] updating codebuild version and adding account id

- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/controller/ContributionAppealController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/dto/ContributionAppealDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/projection/ContributionAmountView.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/service/ContributionAppealService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/ContribAppealRulesEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/ContribAppealRulesRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/contribution/controller/ContributionAppealControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/contribution/service/ContributionAppealServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-373)
Added controller, service, repository and entity for `CONTRIB_APPEAL_RULES`
Added controller and unit test
> Lcam 373 contrib appeal rules endpoint

- maat-court-data-api/src/main/java/gov/uk/courtdata/correspondence/controller/CorrespondenceStateController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/correspondence/dto/CorrespondenceStateDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/correspondence/service/CorrespondenceStateService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/CorrespondenceStateEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/CorrespondenceStateRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/correspondence/controller/CorrespondenceStateControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/correspondence/service/CorrespondenceStateServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-402)
Added controller, service, repository, entity and test classes for `correspondence_state` table
> Lcam 402 cru correspondence state

- maat-court-data-api/src/main/java/gov/uk/courtdata/link/validator/PreConditionsValidator.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/controller/LinkControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/link/validator/PreConditionsValidatorTest.java
- sequence-diagrams/link/link-validate.md
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1924)
> LASB-1924 - Expand link validation endpoint

- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/controller/LinkControllerIntegrationTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1924)
> LASB-1924: Corrected fault in LinkControllerIntegrationTest test data.

- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/contribution/ContributionsControllerIntegrationTest.java
> LCAM-375-testcase fix

- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/contribution/ContributionsControllerIntegrationTest.java
> LCAM-pipeline-testcase fix

- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/contribution/ContributionsControllerIntegrationTest.java
> LCAM-375-fix testcase issue

- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/controller/ContributionCalcController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/dto/ContributionCalcParametersDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/mapper/ContributionsCalcParametersMapper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/service/ContributionCalcService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/ContribCalcParametersEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/ContribCalcParametersRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/contribution/controller/ContributionCalcControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/contribution/service/ContributionCalcServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-393)
Created an end point to retrieve Contribution Calc Parameters for an effective date as per get_contribs_parameters stored procedure in the contributions package.
> LCAM-393|End point to get Contribution Calc Parameters

- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/RepOrderCCOutComeEntity.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-616)
Adding seq for entity 
> LCAM-616-adding seq

- maat-court-data-api/build.gradle
- maat-court-data-api/src/main/java/gov/uk/courtdata/link/service/CreateLinkListener.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/MockServicesExcludingListenerConfig.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/link/service/CreateLinkListenerEndToEndTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/link/service/SqsIntegrationTest.java
- maat-court-data-api/src/test/resources/application.yaml
- scripts/pre_build.sh
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1960)
Integration test for SQS.
Basically works with a few caveats:
- Requires a localstack docker image in the local registry.
- A couple of errors in the logs when running the test around SQS credentials (not really sure why) and shutting down the queue that could be looked in at a future date (the queues are actually shut down but looks like it could be done more gracefully).
> LASB-1960 - integration test for AWS SQS

- README.md
Updated Readme with SQS integration test details.
> Updated Readme with SQS integration test details

- maat-court-data-api/build.gradle
- maat-court-data-api/src/main/java/gov/uk/courtdata/controller/ReservationsController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/converter/BooleanConverter.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/courtdataadapter/client/CourtDataAdapterClient.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/eform/validator/UsnValidator.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/controller/CCOutcomeController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/controller/RepOrderGQLController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/impl/CCOutcomeImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/mapper/CCOutcomeMapper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/service/CCOutcomeService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/service/RepOrderService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/ContribCalcParametersRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/CrownCourtProcessingRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/wqhearing/mapper/WQHearingMapper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/wqhearing/service/WQHearingService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/wqlinkregister/mapper/WQLinkRegisterMapper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/wqlinkregister/service/WQLinkRegisterService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/prosecutionconcluded/helper/ReservationsRepositoryHelperTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/wqhearing/service/WQHearingServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/wqlinkregister/service/WQLinkRegisterServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-2012)
Fixed all latest SQ issues
> LASB-2012 - Resolved latest SonarQube issues with project

- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/controller/HardshipReviewController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/controller/StandardApiResponseCodes.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/impl/HardshipReviewImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/mapper/HardshipReviewMapper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/service/HardshipReviewService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/HardshipReviewRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hardship/controller/HardshipReviewControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hardship/impl/HardshipReviewImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hardship/service/HardshipReviewServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-597)
Create endpoint to retrieve hardship review by detail type.
> LCAM-597|Create endpoint to retrieve hardship review by detail type

- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/controller/ContributionsController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/mapper/ContributionsMapper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/service/ContributionsService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/contribution/controller/ContributionsControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/contribution/service/ContributionsServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/contribution/ContributionsControllerIntegrationTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-408)
Retrieve all contribution by rep id
> LCAM-408-find-contribution

- maat-court-data-api/build.gradle
- maat-court-data-api/src/main/java/gov/uk/courtdata/courtdataadapter/client/CourtDataAdapterClient.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/courtdataadapter/client/CourtDataAdapterOAuth2ClientConfig.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/exception/ApiClientException.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/exception/RetryableWebClientResponseException.java
- maat-court-data-api/src/main/resources/application.yaml
- maat-court-data-api/src/test/java/gov/uk/courtdata/courtdataadapter/client/CourtDataAdapterClientIntegrationTest.java
- maat-court-data-api/src/test/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1973)
Implemented retries for calls to CDA and relevant integration tests.
> LASB-1973 - Implemented Retries for CDA Calls and Integration Tests

- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/FinancialAssessmentDTO.java
> Added Replaced

- aws/application/application.template
> removed the cognito for dces

- aws/application/application.template
Updating a application.template to add a new Cognito client for DECS project. Updated the API Gateway to restrict for its own endpoints. 
> adding a cognito client for DCES service

- aws/application/application.template
> changed the api authorizer name

- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/controller/HardshipReviewController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/impl/HardshipReviewImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/service/HardshipReviewService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/HardshipReviewRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hardship/controller/HardshipReviewControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hardship/impl/HardshipReviewImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hardship/service/HardshipReviewServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-598)
> LCAM-598|Update the return mapping

- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/service/HardshipReviewService.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-598)
> Use CollectionUtils for Null Or Empty check

- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/impl/HardshipReviewImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/service/HardshipReviewService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/HardshipReviewRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hardship/impl/HardshipReviewImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hardship/service/HardshipReviewServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-598)
> Fix the error 500

- aws/application/application.template
> Removed the CMA cognito pool.

- aws/application/application.template
> Recreate CMA cognito pool

- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/service/ContributionsService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/ContributionsDTO.java
> Added Calculation Ran Field to DTO

- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/service/ContributionsService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/ContributionsDTO.java
Reverts ministryofjustice/laa-maat-court-data-api#808
> Revert "Added Calculation Ran Field to DTO"

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-2396)
> LASB-2396: Additional sqs permissions added to the MAAT API EC2 Role

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-2396)
> LASB-2396: Added additional sqs get queue url permission to the EC2 Role

- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/controller/ContributionsController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/repository/ContributionsRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/service/ContributionsService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/contribution/controller/ContributionsControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/contribution/service/ContributionsServiceTest.java
> New endpoint to get Latest Sent Contribution

- maat-court-data-api/src/main/resources/db/changelog/changes/increase_column_various_mla_tables.sql
[LASB-2294](https://dsdmoj.atlassian.net/browse/LASB-2294)
[LASB-2294]: https://dsdmoj.atlassian.net/browse/LASB-2294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LASB-2293] added SQL script

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/browse/LASB.2422)
> LASB-2422: Limit audience for EForms endpoint

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/LASB/boards/454?selectedIssue=LASB-2419)
Extended API Gateway logging for security purposes (see story for more details)
> LASB-2419: Added additional logging parameters to API Gateway

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/LASB/boards/454?selectedIssue=LASB-2419)
Replaced Cognito ID with Principal ID as output was blank
> LASB-2419:Replaced Cognito ID with Principal ID

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-2419?atlOrigin=eyJpIjoiOTU0YzVjYjY2OTVlNDdjZmE0MTg1NzM1MGMxZmY2NzYiLCJwIjoiaiJ9)
Added some additional logging parameters for API Gateway
> LASB-2419: Added client id, caller and claim sub to logging parameters

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/LASB/boards/454?selectedIssue=LASB-2419)
Final changes to logginng
> LASB-2419: Finalise logging changes

- aws/application/application.template
> OAuth Client Crime Validation Service

- maat-court-data-api/build.gradle
- maat-court-data-api/src/main/resources/application.yaml
- maat-court-data-api/src/main/resources/spring-logback.xml
[LCAM-986](https://dsdmoj.atlassian.net/browse/LCAM-986)
- Configured Spring Cloud Sleuth and Spring-logback.xml to enable tracing
[LCAM-986]: https://dsdmoj.atlassian.net/browse/LCAM-986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LCAM-986: 

- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/controller/HardshipReviewController.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1002)
Removed laaTransactionId from Hardship endpoints.
> LCAM-1002|Remove laaTransactionId from Hardship endpoints

- maat-court-data-api/src/main/java/gov/uk/courtdata/service/CrownCourtOutcomeService.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-983)
> LCAM-983-inject repository

- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/authorization/controller/AuthorizationController.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1004)
Removed laaTransactionId from CMA endpoint.
> LCAM-1005|Remove laaTransactionId

- maat-court-data-api/src/main/java/gov/uk/courtdata/enums/HardshipReviewDetailCode.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1011)
> Fixed spelling

- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/hardship/HardshipControllerIntegrationTest.java
[LCAM-1012](https://dsdmoj.atlassian.net/browse/LCAM-1012)
- Fix integration test failures in code pipeline build due to updated/created date-time value
[LCAM-1012]: https://dsdmoj.atlassian.net/browse/LCAM-1012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LCAM-1012: Fix integration tests

- maat-court-data-api/build.gradle
- scripts/build.sh
[LCAM-1012](https://dsdmoj.atlassian.net/browse/LCAM-1012)
- Updated gradle and build.sh for sonar
[LCAM-1012]: https://dsdmoj.atlassian.net/browse/LCAM-1012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LCAM-1012: Updated gradle and build.sh for sonar

- maat-court-data-api/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-2714)
Fix Swagger doc's.
> LASB-2714 - fix Swagger doc's

- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/RepOrderDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/ContributionsEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/IOJAppealEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/RepOrderCCOutComeEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/RepOrderEntity.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/controller/RepOrderControllerTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1059)
Added entity mappings for `RepOrderEntity`, updated Dto and controller test
> LCAM-1059| added entity mappings and controller test

- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/RepOrderDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/ContributionsEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/IOJAppealEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/RepOrderCCOutComeEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/RepOrderEntity.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/controller/RepOrderControllerTest.java
Reverts ministryofjustice/laa-maat-court-data-api#860
> Revert "LCAM-1059| added entity mappings and controller test"

- maat-court-data-api/src/main/java/gov/uk/courtdata/eform/controller/EformStagingController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/eform/dto/EformStagingDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/eform/model/EformStagingResponse.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/eform/repository/entity/EformsStagingEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/eform/service/EformStagingService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/eform/controller/EformStagingControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/eform/service/EformStagingServiceTest.java
[LASB-2661](https://dsdmoj.atlassian.net/browse/LASB-2661)
Adding patch endpoint to update eform staging DB table.
[LASB-2661]: https://dsdmoj.atlassian.net/browse/LASB-2661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LASB-2661] Adding patch endpoint

- maat-court-data-api/build.gradle
- maat-court-data-api/src/main/java/gov/uk/courtdata/eform/controller/EformResultsController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/eform/repository/EformResultsRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/eform/repository/entity/EformResultsEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/eform/service/EformResultsService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/eform/controller/EformResultsControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/eform/service/EformResultsServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-2682)
> LASB-2682 - CRUD controller for eforms_results table

- aws/application/application.template
[LASB-2639](https://dsdmoj.atlassian.net/browse/LASB-2639)
Generate credentials for ATS Service to access MAAT API.
[LASB-2639]: https://dsdmoj.atlassian.net/browse/LASB-2639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LASB-2639] Generate credentials for ATS Service

- aws/application/application.template
> LCAM-1025-fixing-build-issue

- maat-court-data-api/src/main/resources/db/changelog/changes/lasb_2607_create_queue_message_log_index.sql
- maat-court-data-api/src/main/resources/db/changelog/changes/lasb_2607_drop_queue_message_log_index.sql
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-2607)
Scripts for a new index to improve this table's query performance.
> LASB-2607 - create new index for MLA.XXMLA_QUEUE_MESSAGE_LOG

- maat-court-data-api/src/main/java/gov/uk/courtdata/eform/controller/EformStagingController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/eform/service/EformStagingService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/eform/controller/EformStagingControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/eform/service/EformStagingServiceTest.java
[LASB-2861](https://dsdmoj.atlassian.net/browse/LASB-2861)
Passing user id for tracking application
[LASB-2861]: https://dsdmoj.atlassian.net/browse/LASB-2861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LASB-2861] inserting user id for application tracking

- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/service/FinancialAssessmentService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/service/FinancialAssessmentServiceTest.java
> Update Financial Assessments

- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/controller/ReservationsController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/service/ReservationsService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/controller/ReservationsControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/service/ReservationsServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1175)
Created CRUD endpoints on RESERVATIONS table.
> LCAM-1175|Create CRUD endpoints on RESERVATIONS table

- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/controller/ReservationsController.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1175)
Updated the mapping type in the controller.
> Review comments

- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/service/FinancialAssessmentService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/service/FinancialAssessmentServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1096)
Created means assessment rollback endpoint to update the fields selectively in the Financial_Assessments table.
> LCAM-1096|Create means assessment rollback endpoint

- .github/CODEOWNERS
> Update codeowners for laa aws infra

- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/controller/PassportAssessmentController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/service/PassportAssessmentService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/PassportAssessmentEntity.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/controller/PassportAssessmentControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/service/PassportAssessmentServiceTest.java
[LASB-2977](https://dsdmoj.atlassian.net/browse/LASB-2977)
Get Passport Assessor Name API
[LASB-2977]: https://dsdmoj.atlassian.net/browse/LASB-2977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LASB-2977] Get Passport Assessor Name API

- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/controller/PassportAssessmentController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/service/FinancialAssessmentService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/service/PassportAssessmentService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/controller/HardshipReviewController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/service/HardshipReviewService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/controller/FinancialAssessmentControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/controller/PassportAssessmentControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/service/FinancialAssessmentServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/service/PassportAssessmentServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hardship/controller/HardshipReviewControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/hardship/service/HardshipReviewServiceTest.java
[LCAM-1187](https://dsdmoj.atlassian.net/browse/LCAM-1187)
Added patch endpoints to perform partial updates on HardshipReviews and PassportAssessments.
Tidied up existing tests.
[LCAM-1187]: https://dsdmoj.atlassian.net/browse/LCAM-1187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LCAM-1187|Add PATCH endpoints for HardshipReview and PassportAssessments

- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/controller/FdcContributionsController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/response/FdcContributionsGlobalUpdateResponse.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/DebtCollectionRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/DebtCollectionService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/FdcContributionsService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/FdcContributionsRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/DebtCollectionRepositoryTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/FdcContributionsServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/dces/FdcContributionsIntegrationTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-193)
Adding endpoint to be used in the modernised maat-5 job, the "global update" to prime fdc entries for sending to the debt recovery company.
> DCES-193 FDC Global Update

- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/response/FdcContributionEntry.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/FdcContributionsService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/dces/FdcContributionsIntegrationTest.java
Adding maat id to the fdc get call
Adding rep order population and testing of the id.
> DCES-Adding-Maat-Id-To-Fdc-Get

- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/controller/ContributionsController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/repository/ContributionsRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/service/ContributionsService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/contribution/controller/ContributionsControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/contribution/service/ContributionsServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/contribution/ContributionsControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/contribution/ContributionsServiceIntegrationTest.java
> LCAM-1223|Remove redundant code and tidy up tests

- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/controller/ContributionsController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/repository/ContributionsRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/service/ContributionsService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/contribution/controller/ContributionsControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/contribution/service/ContributionsServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1222)
Removed redundant methods and associated tests.
> LCAM-1222|Remove redundant methods and associated tests

- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/RepOrderEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/CreateRepOrder.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/controller/RepOrderController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/service/RepOrderService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestEntityDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/applicant/ApplicantControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/assessment/FinancialAssessmentControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/assessment/PassportAssessmentControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/contribution/ContributionsControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/contribution/ContributionsServiceIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/hardship/HardshipControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/hearing/HearingResultedListenerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/laastatus/service/LaaStatusUpdateControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/controller/LinkControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/service/CreateLinkListenerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/prosecution_concluded/ProsecutionConcludedIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/repOrder/CCOutcomeControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/repOrder/RepOrderCapitalIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/repOrder/RepOrderControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/unlink/controller/UnLinkControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/unlink/service/UnlinkListenerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/laastatus/validator/LaaStatusValidatorTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/controller/RepOrderControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/service/CCOutcomeServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1224)
1) Remove repId from Create application API request
2) Remove validateNotExists() when creating application
3) Adding sequence for repId
4) Fixing all broken integration testing. 
> LCAM-1224-Adding sequence for RepId and fixing broken integration testing

- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/RepOrderEntity.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1224)
> LCAM-1224-change generated strategy to  sequence 

- aws/application/application.template
[LASB-3083](https://dsdmoj.atlassian.net/browse/LASB-3083)
[LASB-3083]: https://dsdmoj.atlassian.net/browse/LASB-3083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LASB-3083] Generate cognito credentials for CCCD

- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/mapper/FinancialAssessmentMapper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/mapper/PassportAssessmentMapper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/FinancialAssessmentDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/mapper/HardshipReviewMapper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/assessment/FinancialAssessment.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/model/hardship/HardshipReview.java
> Valid property

- maat-court-data-api/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1288)
Updated crime commons version to fix serialisation issues in hardship flow.
> Update crime commons version to fix serialisation issues

- .github/workflows/gradle-build-and-test.yml
Fixed the typo in the gradle build workflow yaml
> Fix the typo in the gradle build workflow yaml

- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/controller/ConcorContributionsRestController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/controller/FdcContributionsController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/request/LogFdcProcessedRequest.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/ConcorContributionsService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/DebtCollectionRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/DebtCollectionService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/FdcContributionsService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/util/ContributionFileUtil.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/ContributionFilesEntity.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/dces/mapper/ContributionFileMapperTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/ConcorContributionsServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/DebtCollectionServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/FdcContributionsServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/contribution/ContributionsControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/contribution/ContributionsServiceIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/dces/ConcorContributionsRestControllerIntegTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/dces/FdcContributionsIntegrationTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-287)
Added an endpoint for the DCES service to call when receiving a "process complete" update from the debt recovery company.
Had to rework the saving mechanism for the CONTRIBUTION_FILES entry, as transactional was causing a bug.
> DCES-287 DRC-FDC Response

- maat-court-data-api/src/main/java/gov/uk/courtdata/users/controller/UserSummaryController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/users/service/UserSummaryService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/users/controller/UserSummaryControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/users/service/UserSummaryServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1362)
Added CRUD end points for USERS table.
> LCAM-1362|Create CRUD end points for USERS table

- maat-court-data-api/src/main/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1373)
Reduced logging from Spring Framework to INFO levels and removed logging of JPA queries.
> WIP LCAM 1373 Reconfigure logging levels and jpa query logging

- aws/application/application.template
Adding Get request access for CCCD client
> [LASB-3231] Adding Get request access for CCCD client

- aws/application/application.template
> [LASB-3231] Updating Read scope for CCCD client

- .sonarcloud.properties
- maat-court-data-api/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1358)
> LCAM-1358-add-sonarcloud-property

- aws/application/application.template
> [LASB-3231] Reverting CCCD changes

- aws/application/application.template
> [LASB-3231] Updating scope for CCCD client

- aws/application/application.template
> [LASB-3231] Recreating credential for CCCD with read scope

- maat-court-data-api/src/main/java/gov/uk/courtdata/constants/ErrorCodes.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/exception/RestControllerAdviser.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/StoredProcedureRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/service/StoredProcedureService.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1390)
Implemented the exception handling in the StoredProcedureRepository to be inline with the MAAT application exception handling of the stored procedure calls.
> LCAM-1390|Implement exception handling in StoredProcedure repository

- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/controller/RepOrderController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/RepOrderRepository.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/controller/RepOrderControllerTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3412)
> LASB-3412 - add new endpoint to find MAAT IDs by USN

- maat-court-data-api/src/main/java/gov/uk/courtdata/users/controller/UserSummaryController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/users/service/UserSummaryService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/users/service/UserSummaryServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1357)
Use Entity for patching Users to allow date field updates.
> LCAM-1357|Use Entity for patching Users

- maat-court-data-api/src/main/java/gov/uk/courtdata/users/controller/UserSummaryController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/users/service/UserSummaryService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/users/service/UserSummaryServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1357)
Added End point to allow null updates on Users table.
> LCAM-1357|End point to allow null updates on Users table

- maat-court-data-api/src/main/java/gov/uk/courtdata/service/StoredProcedureService.java
> Added more logs

- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/RepOrderDTO.java
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1459)
- Added iojResult to RepOrderDTO so it will be available when it is called from C3 before checking if contribution need to be calculated.
> LCAM 1459 IoJ Result Not Passed to Check Contribs Condition

- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/validator/CreateContributionsValidator.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/contribution/validator/CreateContributionsValidatorTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1454)
> LCAM-1454-removed transfer status validation

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3457)
> LASB-3457: Add new scope to resource server.

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3457)
> LASB-3457: Added in new scope for DCES clients.

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3457)
> LASB-3457: Updated scope for DCES route in API Gateway

- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/service/ContributionsService.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1477)
> LCAM-1477-default active flag

- maat-court-data-api/src/main/resources/application.yaml
Turn on show-sql option to determine cause of SQL errors when running the functional suite.
> Turn on show-sql option

- .github/workflows/gradle-build-and-test.yml
- scripts/pre_build.sh
> LASB-3486 Include step to verify Git is present

- maat-court-data-api/build.gradle
> LASB- 3486 No fail if.git directory is not present (also check for the .git directory in the parent directory)

- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/RepOrderDTO.java
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1508)
> LCAM 1508 NullPointerException When Referencing UserCreatedEntity in Orchestrator

- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/PassportAssessmentDTO.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3568)
Adding UserCreatedEntity to get passport assessor name
> [LASB-3568] Adding UserCreatedEntity to get passport assessor name

- maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/mapper/HardshipReviewMapper.java
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1540)
> LCAM 1540 Solicitors Costs Not Record on Database When Creating Hardship

- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/controller/RepOrderController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/service/RepOrderService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/controller/RepOrderControllerTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3580)
Added an endpoint to the RepOrderController to return rep order state details. Tested locally with postman and all running as expected. 
> Lasb 3580/get reporder by repid

- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/controller/RepOrderController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/impl/RepOrderImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/service/RepOrderService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/validator/MaatIdValidator.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/repOrder/RepOrderControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/controller/RepOrderControllerTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/impl/RepOrderImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/service/RepOrderServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/validator/MaatIdValidatorTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/Lcam-545)
> LCAM-1545-get-rep-order

- maat-court-data-api/src/main/java/gov/uk/courtdata/contribution/model/CreateContributions.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/ContributionsDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/ContributionsEntity.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestEntityDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1576)
Renamed applId in the Contributions classes as applicantId to be in line with the schema changes.
Removed un-used variables from Test Data Model Builder.
> LCAM-1576|Rename applId as applicantId

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3456)
Added new cognito client for the functional test suite to use.
> [LASB-3456] Add new cognito client for the functional test suite to use.

- aws/application/application.template
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3456)
Added missing audience config for new Functional Test Suite cognito.
> [LASB-3456] Add missing audience config for new Cognito client

- maat-court-data-api/src/main/java/gov/uk/courtdata/applicant/controller/ApplicantController.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/applicant/service/ApplicantHistoryService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/Applicant.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1592)
> LCAM-1592-return applicant history

- maat-court-data-api/src/main/java/gov/uk/courtdata/applicant/dto/RepOrderApplicantLinksDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/applicant/entity/ApplicantHistoryEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/applicant/entity/RepOrderApplicantLinksEntity.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestEntityDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/applicant/ApplicantControllerIntegrationTest.java
Reverts ministryofjustice/laa-maat-court-data-api#1061
> Revert "LCAM-1592"

- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/impl/FinancialAssessmentImpl.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/assessment/mapper/FinancialAssessmentMapper.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/impl/FinancialAssessmentImplTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/assessment/mapper/FinancialAssessmentMapperTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestEntityDataBuilder.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1612)
Retrieve Mandatory flag from existing evidence entity to before updating in the DB.
> LCAM-1612|Retrieve Mandatory flag from entity to populate Evidence DTO

- maat-court-data-api/src/main/resources/db/changelog/changes/lasb_3670_updating_offence_details_for_unknown_offences.sql
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3670)
Updating unknown offences with correct offence details
> [LASB-3670] Updating unknown offences with correct offence details

- aws/application/application.template
Cycling the credentials due to accidental exposure.
> Cycling the credentials for the DCES DRC service.

- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/FeatureToggleDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/entity/FeatureToggleEntity.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/FeatureToggleRepository.java
> Added new column IS_ENABLED

- maat-court-data-api/src/main/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3651)
Currently the info and metrics are exposed. This locks down to expose the now working health endpoint that is required for status checks.
> LASB-3651 - Just expose the health actuator publicly

- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/RepOrderStateDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/mapper/RepOrderMapper.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/mapper/RepOrderMapperTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3784)
Added ccRepDecision to the response sent to Crime Apply for ATIS 
> added cc_rep_decision to rep_order_state

- maat-court-data-api/src/main/java/gov/uk/courtdata/dto/RepOrderStateDTO.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/mapper/RepOrderMapper.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/mapper/RepOrderMapperTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3819)
Map IoJ Appeal details to RepOrderStateDTO for ATIS 
> IoJ Appeal added to rep order state

- maat-court-data-api/start-local.sh
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3767)
Updated startup script to retrieve from shared vault
> Update 1Password vault

- maat-court-data-api/src/main/java/gov/uk/courtdata/repository/ConcorContributionsRepository.java
Removing date_modified from test data selection criteria. Was both un-needed, and causing large timing issues.
> DCES - Test Data Generation - Remove Date Modified Condition.

- maat-court-data-api/docker-compose.yml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3836)
I propose we remove these values as I don't think they're necessary in the docker-compose - they're in the env file that is used by the docker-compose-override - and I think it's better not having them in the repo. 
> Remove environment variables from docker-compose

- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/mapper/FdcMapper.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/ConcorContributionsService.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/DebtCollectionRepository.java
- maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/FdcContributionsService.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/FdcContributionsServiceTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/dces/ConcorContributionsRestControllerIntegrationTest.java
- maat-court-data-api/src/test/java/gov/uk/courtdata/integration/dces/FdcContributionsIntegrationTest.java
Adding additional fields to the fdc fetch in order to assist with Tests.
Adding handling for request for 0 values, returning an empty list.
Lowering the default value for the page size, to more easily avoid the network size limit.
> DCES-Fdc-Fields-Contribution-Minimum

- .github/workflows/cp-deployment.yml
> Update the helm command in the deployment.yml

- helm_deploy/laa-maat-data-api/values-prod.yaml
- helm_deploy/laa-maat-data-api/values-test.yaml
- helm_deploy/laa-maat-data-api/values-uat.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4078)
Updated the JWT Issuer URI in PROD.
> Update the JWT Issuer URI in PROD

- .github/workflows/codeql-analysis.yml
- .github/workflows/cp-deployment-branch.yml
- .github/workflows/cp-deployment.yml
- .github/workflows/gradle-build-and-test.yml
- README.md
- maat-court-data-api/Dockerfile
- maat-court-data-api/build.gradle
- maat-court-data-api/gradle.properties
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4181)
Upgrade MAAT Data API to Use Java 21
> LASB-4181 [MAAT API] Upgrade MAAT Data API to Use Java 21

- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/builder/CourtDataDTOBuilder.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4372)
Fix NPE with the LAA Status Update flow.
> LASB-4372 - Fix NPE with LAA Status Updates

- maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/builder/CourtDataDTOBuilder.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4372)
Fixed the NPE with the legal aid status date when updating the LAA status date.
> LASB-4372 - prevent NPE with legal aid status date

- .github/actions/slack-notify-composite-action/action.yml
- .github/workflows/cp-deployment-branch.yml
- .github/workflows/cp-deployment.yml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4409)
- Add existing webhook URL for the laa-crimeapps-ci Slack channel as a secret to the laa-maat-court-data-api repository
- Create composite github action for slack notification
- Update the deployment workflow to call the composite action after deployment to each environment
> LASB 4409 - Add slack notification
