aws/application/application.template
aws/application/parameters/development-maat-cd-api-pipeline.json
aws/application/parameters/production-maat-cd-api-pipeline.json
aws/application/parameters/staging-maat-cd-api-pipeline.json
aws/application/parameters/test-maat-cd-api-pipeline.json
aws/application/parameters/uat-maat-cd-api-pipeline.json

allow MLRA Fargate instances access to the MAAT-cd-api load balancer
This work is required as part of the MAAT-cd-api implementation

LAWS-775_add-mlra-security-group-access

---

aws/application/application.template

allow MLRA Fargate instances access to the MAAT-cd-api load balancer
This work is required as part of the MAAT-cd-api implementation

LAWS-775_add-mlra-security-group-access-FIX

---

aws/application/application.template

Increase Load Balancer timout by 5 seconds
This is required as the application is not stablizing using the existing
parameters

LAWS-823-Increase-Load-Balancer-Timeout

---

aws/application/application.template

- Change CloudFormation to allow and use the exsiting MAAT database
password parameter
This is required to ensure the password is not kept in multiple
locations

LAWS-823-Change-parameter-source-for-db-password

---

aws/application/application.template

[LAWS-839](https://dsdmoj.atlassian.net/browse/LAWS-839)
- Under ECS-Service, set 'HealthCheckGracePeriodSeconds' to 120 seconds
- Reset Load Balancer health check times to default
This change is required to allow ECS to make database changes on
startup. Without this change the Load Balancer timesout and causes the
application to fail.

LAWS-839-Add-timeout-startup-value-to-ECS

---

maat-court-data-api/src/main/java/gov/uk/courtdata/constants/CourtDataConstants.java
maat-court-data-api/src/main/java/gov/uk/courtdata/entity/XLATOffence.java
maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/magistrate/service/MagistrateCourtService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/processor/WQOffenceProcessor.java
maat-court-data-api/src/main/java/gov/uk/courtdata/link/processor/ResultsInfoProcessor.java
maat-court-data-api/src/main/java/gov/uk/courtdata/link/service/CreateLinkService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/processor/OffenceCodesProcessor.java
maat-court-data-api/src/main/java/gov/uk/courtdata/processor/ResultCodesProcessor.java
maat-court-data-api/src/main/java/gov/uk/courtdata/repository/XLATOffenceRepository.java
maat-court-data-api/src/test/java/gov/uk/courtdata/link/processor/ResultsInfoProcessorTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/processor/OffenceCodesProcessorTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/processor/ResultCodesProcessorTest.java

Result and Offence ref Data Update.
Results and Offence Code should be updated to the ref Data Source during Linking & Hearing Updates. 
New Offence Codes are being updated to XXMLA_XLAT_OFFENCE
New Results Codes are being updated to XXMLA_XLAT_RESULT

Inserting New Result & Offence Codes to the static ref Data Sources

---

maat-court-data-api/src/main/java/gov/uk/courtdata/link/processor/RepOrderCPInfoProcessor.java
maat-court-data-api/src/test/java/gov/uk/courtdata/link/processor/RepOrderCPInfoProcessorTest.java

When linking a case ,the user and time of linking needs be recorded.
On linking a case, the common platform data on maat records the linked caseurn and defendantId.
Along with linked user and time requires be updated. Earlier linking maatId with caseurn was on MAAT and CP tried to 
do the same linking. But with linking from CP is the source for linking a case, the user and time required be recorded. 

When linking a case ,record modified user and time

---

maat-court-data-api/gradle/wrapper/gradle-wrapper.properties

Upgrading gradle version to 6.5.1 so it will be compatible with latest Spring boot version 

Upgrading gradle version 6.5.1

---

aws/application/application.template

Jira [LAWS-976](https://dsdmoj.atlassian.net/browse/LAWS-976
)
- Fix Cloudformation issue where reference in API Gateway Integration
should point to the Load Balancer listener not the balancer itself
This work is required to allow secure access from external
applications

LAWS-976-fix-Cloudformation-ListenerARN-reference

---

maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/processor/WQCoreProcessor.java

https://dsdmoj.atlassian.net/browse/CACP-485
ASN Seq is padded to 3 zeros where required.

Added padding to asn seq on new offence query

---

maat-court-data-api/src/main/java/gov/uk/courtdata/constants/CourtDataConstants.java
maat-court-data-api/src/main/java/gov/uk/courtdata/model/Result.java
maat-court-data-api/src/main/resources/application.yaml

https://dsdmoj.atlassian.net/browse/CACP-500
Setting up Default CJS result Code to 1000
Increasing the Expiry Days to 90. 

Setting Default CJS Code

---

aws/pipeline/maat-cd-api-deployment-pipeline.template
scripts/build.sh

Jira [LAWS-1020](https://dsdmoj.atlassian.net/browse/LAWS-1020)
- Change CodeBuild to run in a private Subnet
- Set CodeBuild Security Group to allow access to SonarQube
- Set CodeBuild to use a specific role, this role will allow access
to specific Parameter Store secrets
- In CodeBuild pass SonarQube user token as Environment Variable
- Update build.sh to change Gradle to run SonarScanner
These changes to maat-cd-api provide SonarQube as a static analysis
tool every time the ECS image is built

LAWS-1020-add-sonarqube-testing-to-codepipeline

---

scripts/build.sh

https://dsdmoj.atlassian.net/browse/CACP-509
sonarqube - remove scm provider property and allow to use artefact from s3.

Sonarqube - remove scm provider and to use artifact from s3

---

maat-court-data-api/src/main/java/gov/uk/courtdata/entity/WqLinkRegisterEntity.java
maat-court-data-api/src/main/java/gov/uk/courtdata/link/processor/WqLinkRegisterProcessor.java

Linking CP cases created date to be recorded with time.
https://dsdmoj.atlassian.net/browse/CACP-522
When common platform cases are linked ,creation date was persisted without time to it which is causing LIBRA MI reports to fail. Fix to persist creation date as date time.   

Modify link created date to time stamp

---

maat-court-data-api/src/main/java/gov/uk/courtdata/entity/WqCoreEntity.java
maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/processor/WQCoreProcessor.java
maat-court-data-api/src/main/java/gov/uk/courtdata/link/processor/WqCoreInfoProcessor.java
maat-court-data-api/src/main/java/gov/uk/courtdata/unlink/impl/UnLinkImpl.java

On events in MLRA created and processed time doesn't include timestamp. 
https://dsdmoj.atlassian.net/browse/CACP-520
Fix to add time to created and processed date on events.

Update wq core create and processed to timestamp

---

maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/builder/CourtDataDTOBuilder.java
maat-court-data-api/src/test/java/gov/uk/courtdata/laastatus/builder/CourtDataDTOBuilderTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-380)
MLRA sending a request to post a message for CSA. If the Legal aid status date is not available then maat-API will set this date before sending to CDA. This is the required fields when the application status is not pending. 

Setting the legal aid date when sending a request to CDA.

---

aws/pipeline/maat-cd-api-deployment-pipeline.template

Amends the manual approval stages in the code pipeline so that the change set is built before the manual approval which allows the changes to be double checked before executing the change set to different environments. (Not needed in development).
Jira - https://dsdmoj.atlassian.net/browse/LAWS-1788

Refactored codepipeline to have the approvals after the changeset and before execution

---

maat-court-data-api/src/main/java/gov/uk/courtdata/exception/GlobalAppLoggingHandler.java
maat-court-data-api/src/main/java/gov/uk/courtdata/hearing/service/HearingResultedService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/helper/RepOrderCPDataHelper.java
maat-court-data-api/src/main/java/gov/uk/courtdata/model/Unlink.java
maat-court-data-api/src/main/java/gov/uk/courtdata/repository/RepOrderCPDataRepository.java
maat-court-data-api/src/main/java/gov/uk/courtdata/service/QueueMessageLogService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/unlink/processor/UnLinkProcessor.java
maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestEntityDataBuilder.java
maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestModelDataBuilder.java
maat-court-data-api/src/test/java/gov/uk/courtdata/hearing/service/HearingResultedServiceTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/helper/RepOrderCPDataHelperTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/unlink/impl/UnLinkImplIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/unlink/service/UnlinkListenerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/unlink/processor/UnLinkProcessorTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/lasb-712)
Updated the Unlinking and Hearing resulted/notification listenrs, the change made to remove the maat-id from the payload and added the defendantId. There is no change with the linking request/listener.  

Removed MaatId from the SQS payload

---

maat-court-data-api/src/main/resources/application.yaml

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-997)
Increase Hikari connection pool size
Turned off SQL output to prevent it from polluting the logs

Increase Hikari connection pool size and turn off SQL output

---

aws/application/parameters/development-maat-cd-api-pipeline.json

Following the rebuild of MLRA dev, this updates the security group id for that app in dev.

Updates mlra ec2 sec group id in development env.

---

aws/application/parameters/test-maat-cd-api-pipeline.json
aws/application/parameters/uat-maat-cd-api-pipeline.json

UAT & Test stacks updated with new MLRA ECS Security Group IDs.
This is required following the rebuild of the MLRA application stacks in test & uat.

UAT & Test stacks updated with new MLRA ECS Security Group IDs.

---

maat-court-data-api/src/main/resources/application.yaml

Increase the Hikari maximum pool size to 50 to prevent the service from running out of available connections in production.

Increase Hikari maximum pool size to 50

---

aws/application/parameters/development-maat-cd-api-pipeline.json
aws/application/parameters/production-maat-cd-api-pipeline.json
aws/application/parameters/staging-maat-cd-api-pipeline.json
aws/application/parameters/test-maat-cd-api-pipeline.json
aws/application/parameters/uat-maat-cd-api-pipeline.json

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-999)

LASB-999: Disabled cloudwatch metrics in all environments.

---

aws/application/application.template

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-998)
Remove link in CloudFormation template causing the following error in AWS:
`Invalid request provided: Create TaskDefinition: Links are not supported when networkMode=awsvpc.`

Remove link in CloudFormation template

---

aws/application/application.template

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-998)
Change was made to address the following error when deploying the application in AWS:
`The sum of all container 'cpu' values cannot be greater than the value of the task 'cpu'`
This was discussed with OPS who suggested upping the available resources.

Update CPU and Memory Resources in TaskDefinition

---

maat-court-data-api/src/test/java/gov/uk/courtdata/integration/prosecution_concluded/ProsecutionConcludedIntegrationTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1101)
-[x] Updated ignored tests to use disabled annotation to work with JUnit 5

LASB-1101 - Update ignored tests.

---

maat-court-data-api/src/main/resources/application.yaml

Updating the txn data retention period from 720 days to 30 days.  

Update data retention period to 30 days

---

.github/CODEOWNERS

This fixes issues with the .CODEOWNERS file that prevented the LAA Ops team from approving infrastructure-related changes. 

This fixes a bug that prevents LAA Ops from approving infrastructure-related changes.

---

maat-court-data-api/src/main/java/gov/uk/courtdata/service/QueueMessageLogService.java
maat-court-data-api/src/test/java/gov/uk/courtdata/service/QueueMessageLogServiceTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1886)

LASB 1886 - Fix JSONNull error queue message log service

---

README.md

Remove large bulk of section on GPG and instead reference more up to date Confluence page which can be a central (non-duplicated) source of truth for git-crypt setup.

Update README.md with better git-crypt guidance

---

maat-court-data-api/src/main/java/gov/uk/courtdata/link/service/CreateLinkListener.java
maat-court-data-api/src/main/java/gov/uk/courtdata/unlink/service/UnlinkListener.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/service/CreateLinkListenerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/unlink/service/UnlinkListenerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/link/service/CreateLinkListenerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/unlink/service/UnlinkListenerTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/lasb-1926)
Updated the code for linking to manage the duplicate and added a try-catch in the case of a validation error. For any other failure the message will be posted back to the SQS but for validation, it will finish the call. This is the same for both linking and unblinking. 
Upgraded the Unlinking SQS listener from JMS to Spring cloud SQS. 

Updated SQS listener from JMS to Spring cloud SQS for Link and unlink

---

maat-court-data-api/src/main/java/gov/uk/courtdata/aspect/XRayInspector.java

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1970)

LASB-1970: Large x-ray segments causing IOExceptions.

---

maat-court-data-api/src/main/java/gov/uk/courtdata/constants/CourtDataConstants.java
maat-court-data-api/src/main/java/gov/uk/courtdata/courtdataadapter/client/CourtDataAdapterClient.java
maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/builder/RepOrderUpdateMessageBuilder.java
maat-court-data-api/src/main/java/gov/uk/courtdata/laastatus/controller/LaaStatusUpdateController.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/laastatus/service/LaaStatusUpdateControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/laastatus/builder/RepOrderUpdateMessageBuilderTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1965)

LASB-1965: Update transaction id header name fo CDA calls

---

aws/pipeline/maat-cd-api-deployment-pipeline.template

Increased build timeout to 25 mins to prevent code pipeline timeout at 15 minutes.

Fix build timeouts in AWS pipeline

---

maat-court-data-api/src/test/java/gov/uk/courtdata/integration/assessment/FinancialAssessmentControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/assessment/PassportAssessmentControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/authorization/AuthorizationControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/contribution/ContributionsControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/correspondence/CorrespondenceStateControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/hardship/HardshipControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/hearing/HearingResultedListenerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/laastatus/service/LaaStatusUpdateControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/controller/LinkControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/impl/SaveAndLinkImplIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/service/CreateLinkCpJobStatusServiceIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/service/CreateLinkListenerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/offence/OffenceControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/prosecution_concluded/ProsecutionConcludedAndHearingIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/prosecution_concluded/ProsecutionConcludedIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/repOrder/CCOutcomeControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/repOrder/RepOrderCapitalIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/repOrder/RepOrderControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/unlink/impl/UnLinkImplIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/unlink/service/UnlinkListenerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/wqhearing/WQHearingControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/wqlinkregister/WQLinkRegisterControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/wqoffence/WQOffenceControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/job/QueueMessageMaintenanceSchedulerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/util/RepositoryUtil.java

[[Link to story](https://dsdmoj.atlassian.net/browse/AP-XXX)](https://dsdmoj.atlassian.net/browse/LASB-1982)
As illustrated by https://github.com/ministryofjustice/laa-maat-court-data-api/pull/739 there is a need to provide a standard and reusable way to correctly tear down/delete contents of all repositories in integration tests. This will reduce duplicate and boiler plate code and help ensure that all repositories are in a clean state following any integration test run.
Changes include:
- Add new Utility class and method `gov.uk.courtdata.util.RepositoryUtil.clearUp`
- Replace duplicated `deleteAll()` and `flush()` calls in tests with a single call to `RepositoryUtil.clearUp()`

LASB-1982 Create RepositoryUtil test utility to standardise clearing down repos correctly after each test

---

aws/application/parameters/development-maat-cd-api-pipeline.json
aws/application/parameters/staging-maat-cd-api-pipeline.json
aws/application/parameters/test-maat-cd-api-pipeline.json
aws/application/parameters/uat-maat-cd-api-pipeline.json

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-835)
Disable prosecution scheduler in lower environment 

LCAM-835-disable-scheduler

---

aws/application/application.template

[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/LASB/boards/454?selectedIssue=LASB-2419)
Updated gateway logging config to be on one line as this failed in cloud formation

LASB-2419:Update config to one line as required by Cloud Formation

---

maat-court-data-api/src/main/java/gov/uk/courtdata/enums/HardshipReviewDetailReason.java

[Link to story LCAM1008](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1008)
[Link to story LCAM1009](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1009)
- Amended HardshipReviewDetailReason remove redundant type property
- Added missing 'Allowable Expense' value to HardshipReviewDetailReason enum

LCAM 1008 & 1009 Refactor Hardship Detail Enums

---

scripts/build.sh

[LCAM-1012](https://dsdmoj.atlassian.net/browse/LCAM-1012)
- Removed the manual sonar scan from build.sh as it is done automatically on merge
[LCAM-1012]: https://dsdmoj.atlassian.net/browse/LCAM-1012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LCAM-1012: Removed the manual sonar scan from build.sh 

---

maat-court-data-api/src/main/java/gov/uk/courtdata/eform/controller/EformsDecisionHistoryController.java
maat-court-data-api/src/main/java/gov/uk/courtdata/eform/repository/EformsDecisionHistoryRepository.java
maat-court-data-api/src/main/java/gov/uk/courtdata/eform/repository/entity/EformsDecisionHistory.java
maat-court-data-api/src/main/java/gov/uk/courtdata/eform/service/EformsDecisionHistoryService.java
maat-court-data-api/src/test/java/gov/uk/courtdata/eform/controller/EformsDecisionHistoryControllerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/eform/service/EformsDecisionHistoryServiceTest.java

[LASB-2681](https://dsdmoj.atlassian.net/browse/LASB-2681)
Adding endpoints to allow CRUD functionality on the eforms_decision_history table
[LASB-2681]: https://dsdmoj.atlassian.net/browse/LASB-2681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LASB-2681] CRUD functionality on the eforms_decision_history table

---

maat-court-data-api/src/main/java/gov/uk/courtdata/eform/controller/EformsHistoryController.java
maat-court-data-api/src/main/java/gov/uk/courtdata/eform/repository/EformsHistoryRepository.java
maat-court-data-api/src/main/java/gov/uk/courtdata/eform/repository/entity/EformsHistory.java
maat-court-data-api/src/main/java/gov/uk/courtdata/eform/service/EformsHistoryService.java
maat-court-data-api/src/test/java/gov/uk/courtdata/eform/controller/EformsHistoryControllerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/eform/service/EformsHistoryServiceTest.java

[LASB-2680](https://dsdmoj.atlassian.net/browse/LASB-2680)
CRUD functionality on the eforms_history table
[LASB-2680]: https://dsdmoj.atlassian.net/browse/LASB-2680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LASB-2680] CRUD functionality on the eforms_history table

---

maat-court-data-api/src/main/resources/db/changelog/changes/lasb_1718_grant_dart_read_permissions.sql
maat-court-data-api/src/main/resources/db/changelog/changes/lasb_1718_grant_dart_read_permissions_rollback.sql

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1718)
Added permissions for the DART_QUERY user to the database changelog as a record of the commands that have now been run on production.

LASB-1718 - DART_QUERY schema permissions

---

maat-court-data-api/src/main/java/gov/uk/courtdata/dao/jackson/LocalDateTimeDeserializer.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dto/application/GenericDTO.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1305)
Using custom deserialiser to match the timestamp format sent from Orchestration.

LCAM-1305|Using custom deserializer

---

aws/application/application.template

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3216)
Expose the Open API/Swagger documentation endpoint in all non-prod environments to allow developers and non-Java developers etc. to discover and explore the endpoints available in the MAAT Court Data API.
Changes include:
- Enable unauthenticated access to the endpoint `/open-api/*` in all non-prod environments via a new `AWS::ApiGatewayV2::Route` called `ApiRouteOpenAPI`.

LASB-3216 Enable Open API/Swagger documentation endpoint in non-prod environments

---

aws/application/application.template

Revert renaming of existing routes as it causes an AWS CodePipeline Deployment failure:
> Resource handler returned message: Route with key ANY /link/validate already exists for this API (Service: AmazonApiGatewayV2; Status Code: 409)
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3216)
Previous PR: https://github.com/ministryofjustice/laa-maat-court-data-api/pull/951
See below screenshots for details:

LASB-3216 Revert renaming of existing routes as it causes an AWS CodePipeline error

---

aws/application/application.template
maat-court-data-api/src/main/resources/application.yaml

Modify springdoc.api-docs.path to align with springdoc.api-docs.swagger-ui.path to minimise the number of paths required to be exposed via AWS ApiGatewayV2
Specifically, change `springdoc.api-docs.path` from `/maat-api` to `/open-api`.
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3216)
See attached for evidence of local testing, note that all paths sit under the parent `/open-api `path.

LASB-3216 Modify springdoc.api-docs.path to align with springdoc.api-docs.swagger-ui.path

---

aws/application/application.template

[LASB-3216](https://dsdmoj.atlassian.net/browse/LASB-3216)
Following testing in Dev [https://maat-cd-api.dev.legalservices.gov.uk/open-api/docs.html](https://maat-cd-api.dev.legalservices.gov.uk/open-api/docs.html) I can see that the base URL `/open-api` is not accessible and is returning a 404 Not Found.
This is because the AWS API Gateway Route does not include the base url `/open-api `only sub-paths e.g. `/open-api/` and `/open-api/docs.html` to resolve this, an additional route has been added for the base Open API URL.
[LASB-3216]: https://dsdmoj.atlassian.net/browse/LASB-3216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LASB-3216 Add missing API Route for the base open-api URL

---

maat-court-data-api/src/main/resources/application.yaml
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/controller/testdata/ConcorContributionsTestDataControllerTest.java
maat-court-data-api/src/test/resources/application.yaml
maat-court-data-api/src/testSqsIntegration/resources/application.yaml

* Changed /api/internal/v1/test-data/debt-collection-enforcement to /api/internal/v1/debt-collection-enforcement/test-data
* This was the existing AWS API Gateway CloudFormation file will cover the test-data services with OAuth
* Without this change, the test-data services always responded 401 Unauthorized in the development env
* Changing the URL (rather than changing the CloudFormation files to add the new prefix) was requested by the Crime Apps team (I spoke with Gangadhar Nitta)
[Test Scenarios for the Contribution Use Cases for the Service](https://dsdmoj.atlassian.net/browse/DCES-333)
Moved URLs around to avoid 401 Unauthorized because the API Gateway did not cover the old URL path.

DCES-333 Changed the URL prefix for DCES test-data services

---

maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/DebtCollectionRepository.java

[Minor fix in the context of DCES-349](https://dsdmoj.atlassian.net/browse/DCES-349)
The existing endpoint `/create-contribution-file` failed with a casting exception because the alphanumeric Oracle `ROWID` key (returned when using `Statement.RETURN_GENERATED_KEYS` flag for the JDBC statement) could not be converted into a `java.lang.Number`.
I'm aware there's a larger task to refactor the DCES endpoints into a more REST-ful structure, but this is a point micro-fix independent of that task.

DCES-349 Fix bug when inserting new rows into contribution_files table

---

maat-court-data-api/src/main/java/gov/uk/courtdata/dces/controller/ConcorContributionsRestController.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/ConcorContributionsService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/repository/ConcorContributionsRepository.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/controller/ConcorContributionsRestControllerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/ConcorContributionsServiceTest.java

Found in the context of developing [DCES_349](https://dsdmoj.atlassian.net/browse/DCES-349)
The updateStatus endpoint that updates a specified count of concor_contribution rows from 'SENT' to a new specified status did not reset the contrib_file_id (which it should do to allow the test to check that the contrib_file_id got set).
> In DCES-349, see validation bullet 'CONTRIB_FILE_ID is populated'. Without this change, then validating this would be pointless.
The service method to set a concor_contribution row to 'SENT' as part of contribution_file creation did not set the userModified to 'DCES' (in fact, it left it unchanged). [TBD, if it should also change the dateModified column.]
> In DCES-349, see validation bullet 'UPDATED_BY = DCES'. Without this change, the user-modified is …

DCES-349 set other concor_contribution fields correctly when update status (and clarify names of the two update-status methods)

---

maat-court-data-api/src/test/java/gov/uk/courtdata/contribution/service/ContributionsServiceTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/applicant/ApplicantControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/applicant/ApplicantDisabilitiesControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/applicant/ApplicantDisabilitiesServiceIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/applicant/ApplicantServiceIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/assessment/PassportAssessmentControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/authorization/AuthorizationControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/correspondence/CorrespondenceStateControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/dces/ConcorContributionsRestControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/eform/EFormIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/job/QueueMessageMaintenanceSchedulerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/controller/LinkControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/impl/SaveAndLinkImplIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/service/CreateLinkCpJobStatusServiceIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/link/service/CreateLinkListenerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/offence/OffenceControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/prosecution_concluded/ProsecutionConcludedAndHearingIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/prosecution_concluded/ProsecutionConcludedIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/repOrder/RepOrderControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/unlink/controller/UnLinkControllerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/unlink/impl/UnLinkImplIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/unlink/service/UnlinkListenerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/users/UserSummaryControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/util/Repositories.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/wqhearing/WQHearingControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/wqlinkregister/WQLinkRegisterControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/wqoffence/WQOffenceControllerIntegrationTest.java

Changes include:
- Replace `assert` with `assertEquals` as Java assertions are disabled by default, see [Using Java Assertions](https://www.baeldung.com/java-assert#conclusion).
- Remove local declaration of Repositories in Integration tests and instead re-use Repositories via the `MockMvcIntegrationTest` e.g. `repos.repOrder.save(TestEntityDataBuilder.getRepOrder());`
- Remove redundant calls to `RepositoryUtil().clearUp(` in integration tests, as this is done automatically by extending `MockMvcIntegrationTest`.
- Remove unused imports of `import gov.uk.courtdata.integration.util.RepositoryUtil;`.

Improve consistency of Integration tests with usage of MockMvcIntegrationTest repos

---

maat-court-data-api/src/main/java/gov/uk/courtdata/dces/controller/ConcorContributionsRestController.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/controller/FdcContributionsController.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/ConcorContributionsService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/FdcContributionsService.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/controller/ConcorContributionsRestControllerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/ConcorContributionsServiceTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/FdcContributionsServiceTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/dces/ConcorContributionsRestControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/dces/FdcContributionsIntegrationTest.java

[DCES-379](https://dsdmoj.atlassian.net/browse/DCES-379) Change contribution_file services to return Integer (not Boolean)
- Clear up confusion of having both HTTP status error code and a Boolean response body which is only sent with HTTP status 200
- Return the contribution_file ID as it is useful information, right now primarily for testing, but maybe for other things in future and use HTTP status codes to report errors
- Update tests to reflect new return type
Needed to be able to write some of the tests like DCES-354 and DCES-357, etc.
See also ministryofjustice/laa-dces-drc-integration#46, this should be merged before that.
(Branch name was a typo -should say `379`).
[DCES-354]: https://dsdmoj.atlassian.net/browse/DCES-354?atlOrigin=eyJpIjoiNWR …

DCES-379 Change contribution_file services to return Integer (not Boolean)

---

maat-court-data-api/src/test/java/gov/uk/courtdata/integration/applicant/ApplicantControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/assessment/FinancialAssessmentControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/assessment/PassportAssessmentControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/authorization/AuthorizationControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/contribution/ContributionsControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/contribution/ContributionsServiceIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/correspondence/CorrespondenceStateControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/hardship/HardshipControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/hearing/HearingResultedListenerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/laastatus/service/LaaStatusUpdateControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/repOrder/CCOutcomeControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/repOrder/RepOrderCapitalIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/repOrder/RepOrderControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/util/Repositories.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/wqlinkregister/WQLinkRegisterControllerIntegrationTest.java

Final PR to replace usages of `@Autowired` repositories in Integration tests with usages of the `Repositories` class accessable via `MockMvcIntegrationTest`.
e.g.
```
@Autowired
private RepOrderRepository repOrderRepository;
```
becomes
`repos.repOrder`
Continuation of: https://github.com/ministryofjustice/laa-maat-court-data-api/pull/990

Improve consistency of usage of Repositories in Integration tests

---

maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/controller/RepOrderController.java
maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/impl/RepOrderImpl.java
maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/service/RepOrderService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/repository/RepOrderRepository.java
maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestEntityDataBuilder.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/repOrder/RepOrderControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/controller/RepOrderControllerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/impl/RepOrderImplTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/service/RepOrderServiceTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/DCES-368)
Adding 2 endpoints for use in testing by the Debt Collection & Enforcement Service team. 
Endpoints will be used to validate the Final Defence Cost Global Update sql statements via integration testing. 
These endpoints return Rep Orders which are candidates for both halves of the Global Update, which can be further modified by other endpoints developed separately.

DCES-368 Endpoint for Rep Order Candidates for Fdc Delayed Pickup and Fdc Fast Track

---

maat-court-data-api/src/main/java/gov/uk/courtdata/dces/controller/ContributionFileController.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/mapper/ContributionFileMapper.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/response/ContributionFileErrorResponse.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/response/ContributionFileResponse.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/ContributionFileService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/repository/ContributionFileErrorsRepository.java
maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestEntityDataBuilder.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/controller/ContributionFileControllerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/mapper/ContributionFileMapperTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/ContributionFileServiceTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/dces/ContributionFileControllerIntegrationTest.java

* [DCES-335](https://dsdmoj.atlassian.net/browse/DCES-335) Add endpoints to get contribution_file and contribution_file_error entities by ID
- Add REST controller and simple service for DCES endpoints
- Add DTO (`-Response`) classes for the endpoints (which currently mirror the entities)
- Extend the contribution_file_error repository to allow getting all errors for a file
* DCES-335 Add unit tests for contribution_file endpoints
- Add test entity creation to the `TestEntityDataBuilder` class used by tests
- Add `MockMvc` based `@SpringBootTest` to test the controller
- Add Mockito based vanilla unit test for the service class and changes to the mapper
* DCES-335 Add Swagger annotations to document controller endpoints
- Add `@Tag`, `@Operation`, `@ApiResponse` annotations to document …

DCES-335 Add endpoints to get contribution_file and contribution_file_error entities by ID

---

maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/DebtCollectionRepository.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/FdcContributionsService.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/DebtCollectionRepositoryTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/FdcContributionsServiceTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/DCES-381)
Changing naming for GlobalUpdate submethods with proper naming. Changing away from nondescript merge1 and merge2

DCES-381 - Global Update naming conventions.

---

.github/workflows/codeql-analysis.yml
.github/workflows/gradle-build-and-test.yml
maat-court-data-api/gradle/wrapper/gradle-wrapper.properties

Changes include:
- Uplift from Gradle `7.6` to `8.5`.
- Uplift Gradle GitHub action plugin to `v4.0.0-rc.1`
- Uplift Gradle GitHub checkout action from `v2` to `v4`.

LASB-3486 Uplift to use Gradle 8.5 along with updated GitHub actions

---

maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/DebtCollectionService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/repository/ContributionFilesRepository.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/DebtCollectionServiceTest.java

[DCES-429](https://dsdmoj.atlassian.net/browse/DCES-429) Improve performance of contribution file updates
- Add specific increment of recordsReceived to Repository
- Update Service to use Repository class instead of Entity
- Simplify tests given simpler implementation
[DCES-429]: https://dsdmoj.atlassian.net/browse/DCES-429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DCES-429 Improve performance of contribution file updates

---

maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/impl/HardshipReviewImpl.java
maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/mapper/HardshipReviewMapper.java

[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1526)
- @InheritInverseConfiguration annotation wasn't enough to map hardship status when mapping from DTO to Entity for a Hardship Review so added a custom mapper to help Mapstruct along.

LCAM 1526 Fix Integrity Constraint Violation on Status When Creating In Progress Hardship

---

maat-court-data-api/src/main/java/gov/uk/courtdata/dto/FinancialAssessmentDTO.java

[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1527)
- UserCreatedEntity was being reference in orchestrator to construct meansAssessorName for the request to CAT service. However whilst this variable is present in the MeansAssessmentDTO object in orchestrator, it isn't in maat-api and so wasn't being returned cause a NPE. I've added this variable to the MeansAssessmentDTO to ensure it is returned.

LCAM 1527 Null Pointer Exception When Building Means Assessor Name in Orchestrator

---

maat-court-data-api/src/main/java/gov/uk/courtdata/entity/HardshipReviewDetailEntity.java
maat-court-data-api/src/main/java/gov/uk/courtdata/model/hardship/HardshipReviewDetail.java

[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1528)
- Allowed active for HardshipReviewDetail to be deserialised so that we can pass a value of Y through from the hardship service when creating a hardship review.

LCAM 1528 Hardship Details Not Being Set to Active on Database

---

maat-court-data-api/src/main/java/gov/uk/courtdata/hardship/impl/HardshipReviewImpl.java
maat-court-data-api/src/test/java/gov/uk/courtdata/hardship/impl/HardshipReviewImplTest.java

[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1536)
- Added a null check to the update hardship review logic to set the appropriate solicitors costs fields in the hardship review entity to null if no solicitors costs have been entered.

LCAM 1536 Null Pointer Exception Updating Hardship With No Solicitors Costs

---

maat-court-data-api/src/main/java/gov/uk/courtdata/dto/FeatureToggleDTO.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dto/UserSummaryDTO.java
maat-court-data-api/src/main/java/gov/uk/courtdata/entity/FeatureToggleEntity.java
maat-court-data-api/src/main/java/gov/uk/courtdata/mapper/FeatureToggleMapper.java
maat-court-data-api/src/main/java/gov/uk/courtdata/repository/FeatureToggleRepository.java
maat-court-data-api/src/main/java/gov/uk/courtdata/service/FeatureToggleService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/users/mapper/UserSummaryMapper.java
maat-court-data-api/src/main/java/gov/uk/courtdata/users/service/UserSummaryService.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/users/UserSummaryControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/util/Repositories.java
maat-court-data-api/src/test/java/gov/uk/courtdata/users/service/UserSummaryServiceTest.java

This PR adds feature flag memberships to the user summary information, both for user-specific memberships and for those which apply to all users.
This update is made to allow for changes in services which use feature flags to control logic and specifically, to remove the need to pass feature flag information between services (such as between MAAT and the Orchestration Service). The feature flag information is added specifically to the `UserSummaryDTO` as this is the most appropriate place to hold this information, similar to that held already for role data items.
[Part of LCAM-1342](https://dsdmoj.atlassian.net/browse/LCAM-1342)

Add feature flag memberships to user summary information

---

README.md
maat-court-data-api/src/main/java/gov/uk/courtdata/applicant/controller/ApplicantController.java
maat-court-data-api/src/main/java/gov/uk/courtdata/applicant/service/ApplicantService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/entity/Applicant.java
maat-court-data-api/src/test/java/gov/uk/courtdata/applicant/controller/ApplicantControllerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/applicant/service/ApplicantServiceTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1585)
Update the Applicant create end point to ensure that an applicant is created using the correct sequence as per the current DB and returning the created applicant to the client so that the client will have the generated Applicant ID.
Tidied up the tests; and updated README with the correct script used to run the application locally.

LCAM-1585|Fix the Applicant create functionality

---

maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/ConcorContributionsService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/FdcContributionsService.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/controller/ConcorContributionsRestControllerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/controller/FdcContributionsControllerTest.java

[DCES-52](https://dsdmoj.atlassian.net/browse/DCES-592) Handle acknowledgement for unSENT or missing contributions
- MAAT court data API to produce predictable error code when contribution_file is missing.

DCES-592 Predictable error code on missing contribution_file

---

maat-court-data-api/src/main/java/gov/uk/courtdata/dces/controller/ConcorContributionsRestController.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/ConcorContributionsService.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/controller/ConcorContributionsRestControllerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/ConcorContributionsServiceTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/DCES-665)
DCES-665: Added new get endpoint to get a single concor-contribution-file for the given concor-contribution-id.

DCES-665: Added new get endpoint to get a single concor-contribution-file

---

maat-court-data-api/src/main/java/gov/uk/courtdata/dces/controller/ConcorContributionsRestController.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/controller/FdcContributionsController.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/ConcorContributionsService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/FdcContributionsService.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/controller/ConcorContributionsRestControllerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/controller/FdcContributionsControllerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/ConcorContributionsServiceTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/FdcContributionsServiceTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/DCES-667)
Added 2 new endpoints viz /debt-collection-enforcement/fdc-contributions and /debt-collection-enforcement/concor-contribution-xml to get the FDC and Concor contributions data for a given list of IDs.
Found and fixed an issue whereby some fields (e.g. STATUS, JUD_APPORTION_PERCENT etc), were not mapped and hence not returned by the endpoint /debt-collection-enforcement/fdc-contribution-files.

DCES-667: Added new endpoints to get FDC and Concor contributions for a given set of IDs.

---

maat-court-data-api/src/main/java/gov/uk/courtdata/dces/mapper/FdcContributionMapper.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/FdcContributionsService.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/FdcContributionsServiceTest.java

Fixing issue with mapper not mapping repOrder on the response objects.

DCES-Fdc-Mapper-Rep-Order-Fix

---

maat-court-data-api/src/main/java/gov/uk/courtdata/dces/mapper/FdcMapper.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/DebtCollectionRepository.java
maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/FdcContributionsService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/entity/FdcContributionsEntity.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/FdcContributionsServiceTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/DCES-694)
Refactoring the FDC get endpoints to use a native query.
Under current JPA method, if there are 200 Fdc Contributions found by the FindBy, when we map the object over to the response object. It will then perform 200 additional database queries to populate the RepOrderEntities.
While these are very simple queries ( select * from RepOrder where id = ? ) it both takes extra time, and hits the db unexpectedly.
The native query, and mapper will remove that additional burden, and keeps the response to what is needed.
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after …

DCES-694-Fdc-Fetch-Rework

---

maat-court-data-api/src/main/java/gov/uk/courtdata/dto/RepOrderStateDTO.java
maat-court-data-api/src/main/java/gov/uk/courtdata/reporder/mapper/RepOrderMapper.java
maat-court-data-api/src/test/java/gov/uk/courtdata/reporder/mapper/RepOrderMapperTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3908)
As part of the enhancement to the LAA Crime Applications Adapter, we need to include the Work Reason Code field from the means_test in the API response. Added the meansWorkReason & passportWorkReason field in the response

LASB-3908 [CAA & MAAT API] Adding field Means & Passport Work Reasons of the means_test to the API result

---

maat-court-data-api/src/main/java/gov/uk/courtdata/repository/StoredProcedureRepository.java
maat-court-data-api/src/test/java/gov/uk/courtdata/repository/StoredProcedureRepositoryTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3907)
Added validation for the MAAT API stored procedure endpoint to prevent SQL injection attacks.

LASB-3907 - prevent SQL injection attacks

---

maat-court-data-api/src/main/resources/application.yaml

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1812)
Set `jpa.show-sql` to false in the Court Data API configuration to reduce excessive log noise from SQL statements.

LCAM-1812: Disable Hibernate SQL Logging

---

maat-court-data-api/src/main/java/gov/uk/courtdata/billing/controller/MaatReferenceExtractionController.java
maat-court-data-api/src/main/java/gov/uk/courtdata/billing/entity/MaatReferenceEntity.java
maat-court-data-api/src/main/java/gov/uk/courtdata/billing/entity/MaatReferenceId.java
maat-court-data-api/src/main/java/gov/uk/courtdata/billing/repository/MaatReferenceRepository.java
maat-court-data-api/src/main/java/gov/uk/courtdata/billing/service/MaatReferenceService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/exception/RecordsAlreadyExistException.java
maat-court-data-api/src/main/java/gov/uk/courtdata/exception/RestControllerAdviser.java
maat-court-data-api/src/main/resources/application.yaml
maat-court-data-api/src/test/java/gov/uk/courtdata/billing/controller/MaatReferenceExtractionControllerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/billing/service/MaatReferenceServiceTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/builder/TestEntityDataBuilder.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/billing/MaatReferenceExtractionControllerIntegrationTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/util/Repositories.java
maat-court-data-api/src/test/resources/application.yaml

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4220)
Added a new endpoint "populate-maat-references" to populate a new table "MAAT_REFS_TO_EXTRACT" with required data from the "REP_ORDERS" table. This task is part of the replacement of one of the hub jobs. 

[LASB-4220] Create new endpoint to populate MAAT_REFS_TO_EXTRACT table

---

maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/ConcorContributionsService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/repository/ConcorContributionsRepository.java
maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/ConcorContributionsServiceTest.java

DRC-Integration was having issues with timeouts on the integration tests. Have made modifications to the long call to attempt to remedy this. 
Change process for fetching ConcorContributions to find the ids first, then use a second query to fetch the details.
This will affect the main DRC-Integration process as well, and has been verified by running the integration tests, which are now passing. However an eye will have to be kept to ensure things are being sent exactly as before.
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of …

LASB-4235 - DRC Integration Tests Timeout Fix

---

maat-court-data-api/src/main/java/gov/uk/courtdata/billing/controller/RepOrderBillingController.java
maat-court-data-api/src/main/java/gov/uk/courtdata/billing/request/UpdateRepOrderBillingRequest.java
maat-court-data-api/src/main/java/gov/uk/courtdata/billing/service/RepOrderBillingService.java
maat-court-data-api/src/main/java/gov/uk/courtdata/repository/RepOrderRepository.java
maat-court-data-api/src/test/java/gov/uk/courtdata/billing/controller/BillingApplicantControllerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/billing/controller/RepOrderBillingControllerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/billing/service/RepOrderBillingServiceTest.java

This PR adds a new endpoint to reset rep orders for billing, setting the `SEND_TO_CCLF` flag on relevant rep orders in the database to `null` and updating the date and user modified values alongside.
This behaviour is migrated from the existing `reporder_clear_flag` stored procedure in the MAAT database which was previously called as part of the regular data extraction Hub job.
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4228)

Add endpoint to reset rep orders for billing

---

maat-court-data-api/src/main/java/gov/uk/courtdata/repository/RepOrderRepository.java

This PR adds missing schema references to a recently added query to extract rep orders to send to CCLF.
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4223)

Add missing schema reference to rep order query

---

maat-court-data-api/src/main/java/gov/uk/courtdata/billing/controller/MaatReferenceExtractionController.java
maat-court-data-api/src/main/java/gov/uk/courtdata/billing/repository/MaatReferenceRepository.java
maat-court-data-api/src/main/java/gov/uk/courtdata/billing/service/MaatReferenceService.java
maat-court-data-api/src/test/java/gov/uk/courtdata/billing/controller/MaatReferenceExtractionControllerTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/billing/service/MaatReferenceServiceTest.java
maat-court-data-api/src/test/java/gov/uk/courtdata/integration/billing/MaatReferenceExtractionControllerIntegrationTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4229)
Added endpoint to delete all entries from maat_refs_to_extract table. 
Please note, I went with a DELETE sql command rather than TRUNCATE. I did this because it appears that only the table owner can truncate, or a user with the "drop any table" privilege; there is no way to grant a truncate privilege to a specific user like with select, delete etc. It is technically less-efficient to do it this way, but performance-wise it was negligible; I still managed to delete 267k records in half a second, and there shouldn't ever be more than that given this will run weekly.
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiT …

[LASB-4229] Add endpoint to delete all entries from maat_refs_to_extract

---

.github/workflows/gradle-build-and-test.yml

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4268)
There is a bug with the build and test step regarding caching when merging to main. Setting this gradle setup to v4 instead of the SHA commit it had previously to see if this fixes the issue. Regardless, it is better to be explicit about the version we are using, even if it doesn't fix this particular issue. 

[LASB-4268] Update the setup-gradle version to explicit version 4

---

maat-court-data-api/src/main/java/gov/uk/courtdata/repository/OffenceRepository.java

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4373)
**Improved Performance of the query**
In Oracle, ROWNUM is applied before ORDER BY. So the queries I've changed originally:
- grabs the first matching row it stumbles upon (no ordering), then
- “orders” that single row (a no-op).
Because the optimizer can’t use the ORDER BY TX_ID DESC to get the latest row efficiently, it may end up scanning a lot of blocks (or even the table) until it finds any match. On a big table that’s exactly the kind of sporadic ~minute latency we're seeing. In SQL Developer I ran a version that orders first and limits after, which is fast - 0.029 seconds.
**Fixed the getting of the first (max) TX_ID:**
WHERE ROWNUM = 1 is applied before ORDER BY, while FETCH FIRST 1 ROW ONLY is applied after the sort. …

LASB-4373 - fixed and improved performance of Offence native query
